# Customer Feature Engineering

# Shipment Feature Engineering

In [41]:
import pandas as pd
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [42]:
import pandas as pd 
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [43]:
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [44]:
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [45]:
delivery_labels_cleaned = pd.read_csv("cleaned_supplyguard_data/delivery_labels_cleaned.csv")
delivery_labels_cleaned

        Unnamed: 0  delivery_id  is_late             risk_reason
0                0  DL000000001        1  Long delivery distance
1                1  DL000000002        0         Normal delivery
2                2  DL000000003        0         Normal delivery
3                3  DL000000004        0         Normal delivery
4                4  DL000000005        0         Normal delivery
...            ...          ...      ...                     ...
999995      999995  DL000999996        0         Normal delivery
999996      999996  DL000999997        0         Normal delivery
999997      999997  DL000999998        0         Normal delivery
999998      999998  DL000999999        0         Normal delivery
999999      999999  DL001000000        0         Normal delivery

[1000000 rows x 4 columns]

In [46]:
shipdeliv = pd.merge(
    shipments_cleaned, 
    deliveries_cleaned,
    on = "shipment_id" ,
    how = "left"

)

In [47]:
shipdeliv

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [48]:
finalmerge = shipdeliv.merge(delivery_labels_cleaned)

In [49]:
finalmerge

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,Delivered Late,16.60,935.04,2504.92,2.30,3,9,0,1,Long delivery distance
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,Delivered,1.06,57.08,115.77,3.30,1,12,1,0,Normal delivery
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,Delivered,7.56,402.48,891.87,4.09,1,19,2,0,Normal delivery
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,Delivered,3.35,147.70,609.51,3.68,1,16,3,0,Normal delivery
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,Delivered,1.81,54.77,122.58,4.18,1,17,4,0,Normal delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,Delivered,1.33,64.93,202.73,4.04,1,6,999995,0,Normal delivery
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,Delivered,3.63,261.61,946.81,4.29,2,16,999996,0,Normal delivery
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,Delivered,2.01,100.67,371.75,4.38,1,13,999997,0,Normal delivery
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,Delivered,1.17,58.36,157.25,4.64,1,5,999998,0,Normal delivery
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,Delivered,4.37,217.80,695.03,4.57,1,17,999999,0,Normal delivery

In [54]:
finalmerge['shipment_weight'] = (
    finalmerge.groupby('shipment_id')['weight_kg']
    .transform('sum')
)

In [55]:
finalmerge['shipment_distance'] = (
    finalmerge.groupby('shipment_id')['distance_km']
    .transform('sum')
)

In [56]:
finalmerge['delivery_duration'] = (
    finalmerge.groupby('delivery_id')['delivery_duration_hours']
    .transform('sum')
)

In [57]:
finalmerge['late_delivery_flag'] = (
    finalmerge.groupby('delivery_id')['is_late']
    .transform('sum')
)

In [58]:
finalmerge

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2.30,3,9,0,1,Long delivery distance,11.97,926.17,16.60,1
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,3.30,1,12,1,0,Normal delivery,73.29,63.22,1.06,0
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,4.09,1,19,2,0,Normal delivery,90.70,374.86,7.56,0
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,3.68,1,16,3,0,Normal delivery,13.26,148.44,3.35,0
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,4.18,1,17,4,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,4.04,1,6,999995,0,Normal delivery,5.33,59.99,1.33,0
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,4.29,2,16,999996,0,Normal delivery,7.11,235.68,3.63,0
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,4.38,1,13,999997,0,Normal delivery,12.26,100.23,2.01,0
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,4.64,1,5,999998,0,Normal delivery,10.37,46.44,1.17,0
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,4.57,1,17,999999,0,Normal delivery,14.78,185.89,4.37,0

In [78]:
finalmerge[["shipment_id", "shipment_weight", "shipment_distance", "delivery_duration", "late_delivery_flag"]].drop_duplicates().merge(shipments_cleaned).to_csv("final_data/shipment_final.csv")

In [ ]:
#finalmerge.columns.tolist()
#Checking the names of the colums

# Delivery Feature Engineering

In [ ]:
#finalmerge.columns.tolist()  #To check the names of the coloums

In [63]:
finalmerge["delivery_date"] = pd.to_datetime(
    finalmerge["delivery_date"] , 
    errors="coerce"
)

In [ ]:
#Step 1 - Convert delivery day to a proper datetime format 
finalmerge[["delivery_date", "delivery_hour"]].head()

  delivery_date  delivery_hour
0    2025-12-16              9
1    2025-03-22             12
2    2026-06-26             19
3    2026-07-21             16
4    2025-07-16             17

In [ ]:
#Step 2- delivery weekday  - return the date in text format. 
finalmerge["delivery_weekday"] = finalmerge["delivery_date"].dt.day_name()

In [ ]:
#Check: if Step 2 works 
finalmerge[["delivery_date" , "delivery_weekday"]].head()

  delivery_date delivery_weekday
0    2025-12-16          Tuesday
1    2025-03-22         Saturday
2    2026-06-26           Friday
3    2026-07-21          Tuesday
4    2025-07-16        Wednesday

In [69]:
#Step 3 - Customer_shipment_count 

finalmerge["customer_shipment_count"]= (
    finalmerge.groupby("customer_id")["shipment_id"]
    .transform("count")
)

In [70]:
#Check: Step 3 
finalmerge[["customer_id", "shipment_id", "customer_shipment_count"]].head(10)

  customer_id shipment_id  customer_shipment_count
0     C063536  S000000001                        6
1     C054654  S000000002                        9
2     C075489  S000000003                       12
3     C041283  S000000004                       14
4     C019038  S000000005                       11
5     C081397  S000000006                       12
6     C050317  S000000007                       10
7     C053342  S000000008                        7
8     C017822  S000000009                       11
9     C021120  S000000010                        8

In [ ]:
#Step 4: Custome_average_delivery_time  - round up the delivery time to the next interger. 
#Make use of delivery_duration_hours 

finalmerge["customer_average_delivery_time"] = (
    finalmerge.groupby("customer_id")["delivery_duration_hours"]
    .transform("mean")
)

In [72]:
#Check: Step 4 
finalmerge[["customer_id", "delivery_duration_hours", "customer_average_delivery_time"]].head(10)

  customer_id  delivery_duration_hours  customer_average_delivery_time
0     C063536                    16.60                        4.225000
1     C054654                     1.06                        3.161111
2     C075489                     7.56                        6.170833
3     C041283                     3.35                        6.772857
4     C019038                     1.81                       13.041818
5     C081397                     2.40                       10.572500
6     C050317                     5.36                        6.404000
7     C053342                     1.21                        4.777143
8     C017822                     1.87                        6.778182
9     C021120                     3.38                       11.095000

In [74]:
#Step 5: Distance vs Average
#Dataset: delivery_distance_km

#First caculate the average delivery distance for each customer 

finalmerge["customer_average_distance"] = (
    finalmerge.groupby("customer_id")["delivery_distance_km"]
    .transform("mean")
)

#Second caculate the distance vs average 
finalmerge["distance_vs_average"] =(
    finalmerge["delivery_distance_km"] / finalmerge["customer_average_distance"]
)

In [75]:
#Check: Step 5
finalmerge[["customer_id", "delivery_distance_km", "customer_average_distance", "distance_vs_average"]].head(10)

,customer_id,delivery_distance_km,customer_average_distance,distance_vs_average
0,C063536,935.04,230.100000,4.063625
1,C054654,57.08,152.032222,0.375447
2,C075489,402.48,338.757500,1.188107
3,C041283,147.70,380.225000,0.388454
4,C019038,54.77,759.037273,0.072157
5,C081397,140.84,600.650000,0.234479
6,C050317,256.91,351.007000,0.731923
7,C053342,77.52,262.270000,0.295573
8,C017822,76.02,380.514545,0.199782
9,C021120,97.25,631.255000,0.154058

In [ ]:
#Step 6 - delivery delay hours 
#How many hours late was the delivery compared with when it was expected

Ended here - 20/08/2026 at 12:16 AM.