# Customer Feature Engineering

In [438]:
import pandas as pd
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [439]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [440]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [441]:
#Merging datasets (customers & shipments)
mergedcusship = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [442]:
all3merged = mergedcusship.merge(deliveries_cleaned)

In [443]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,D009146,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,D009897,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,D002742,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,D004317,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,D005469,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,D007343,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,D005723,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,D000789,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,D007516,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,D009458,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6

In [444]:
#Customer shipment count
all3merged['customer_shipment_count'] = (
all3merged.groupby('customer_id')['shipment_id']
.transform('count')
)

In [445]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6

In [446]:
#Creating customer total shipments
all3merged['customer_total_shipping_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'] 
.transform('sum')
)

In [447]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31

In [448]:
#Creating customer average shipment
all3merged['customer_average_shipment_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'].
transform('mean')
)

In [449]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667

In [450]:
all3merged['customer_average_delivery_time'] = (
all3merged.groupby('customer_id')['delivery_duration_hours']
.transform('mean')
)

In [451]:
#All 4 features
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [452]:
#all3merged[["customer_id","customer_shipment_count","customer_total_shipping_value","customer_average_shipment_value","customer_average_delivery_time"]].drop_duplicates().merge(customers_cleaned).to_csv("final_data/customer_final.csv")

# Shipment Features

In [453]:
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [454]:
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [455]:
delivery_labels_cleaned = pd.read_csv("cleaned_supplyguard_data/delivery_labels_cleaned.csv")
delivery_labels_cleaned

        delivery_id  is_late             risk_reason
0       DL000000001        1  Long delivery distance
1       DL000000002        0         Normal delivery
2       DL000000003        0         Normal delivery
3       DL000000004        0         Normal delivery
4       DL000000005        0         Normal delivery
...             ...      ...                     ...
999995  DL000999996        0         Normal delivery
999996  DL000999997        0         Normal delivery
999997  DL000999998        0         Normal delivery
999998  DL000999999        0         Normal delivery
999999  DL001000000        0         Normal delivery

[1000000 rows x 3 columns]

In [456]:
shipdeliv = pd.merge(
    shipments_cleaned,
    deliveries_cleaned,
    on="shipment_id",
    how="left"
)

In [457]:
shipdeliv

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [458]:
finalmerge = shipdeliv.merge(delivery_labels_cleaned)

In [459]:
finalmerge

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,is_late,risk_reason
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1,Long delivery distance
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,0,Normal delivery
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,0,Normal delivery
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,0,Normal delivery
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,0,Normal delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,0,Normal delivery
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,0,Normal delivery
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,0,Normal delivery
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,0,Normal delivery
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,0,Normal delivery

In [460]:
finalmerge['shipment_weight'] = (
finalmerge.groupby('shipment_id')['weight_kg']
.transform('sum')
)

In [461]:
finalmerge['shipment_distance'] = (
finalmerge.groupby('shipment_id')['distance_km']
.transform('sum')
)

In [462]:
finalmerge['delivery_duration'] = (
finalmerge.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [463]:
finalmerge['late_delivery_flag'] = (
finalmerge.groupby('delivery_id')['is_late']
.transform('sum')
)

In [464]:
finalmerge

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2504.92,2.30,3,9,1,Long delivery distance,11.97,926.17,16.60,1
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,115.77,3.30,1,12,0,Normal delivery,73.29,63.22,1.06,0
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,891.87,4.09,1,19,0,Normal delivery,90.70,374.86,7.56,0
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,609.51,3.68,1,16,0,Normal delivery,13.26,148.44,3.35,0
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,122.58,4.18,1,17,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,202.73,4.04,1,6,0,Normal delivery,5.33,59.99,1.33,0
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,946.81,4.29,2,16,0,Normal delivery,7.11,235.68,3.63,0
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,371.75,4.38,1,13,0,Normal delivery,12.26,100.23,2.01,0
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,157.25,4.64,1,5,0,Normal delivery,10.37,46.44,1.17,0
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,695.03,4.57,1,17,0,Normal delivery,14.78,185.89,4.37,0

In [465]:
#finalmerge[["shipment_id","shipment_weight","shipment_distance","delivery_duration","late_delivery_flag"]].drop_duplicates().merge(shipments_cleaned).to_csv("final_data/shipment_final.csv", index=False)

# Delivery Feature Engineering

In [466]:
import pandas as pd
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [467]:
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [468]:
deliveries_cleaned["delivery_weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [469]:
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [470]:
finalmerge

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2504.92,2.30,3,9,1,Long delivery distance,11.97,926.17,16.60,1
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,115.77,3.30,1,12,0,Normal delivery,73.29,63.22,1.06,0
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,891.87,4.09,1,19,0,Normal delivery,90.70,374.86,7.56,0
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,609.51,3.68,1,16,0,Normal delivery,13.26,148.44,3.35,0
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,122.58,4.18,1,17,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,202.73,4.04,1,6,0,Normal delivery,5.33,59.99,1.33,0
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,946.81,4.29,2,16,0,Normal delivery,7.11,235.68,3.63,0
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,371.75,4.38,1,13,0,Normal delivery,12.26,100.23,2.01,0
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,157.25,4.64,1,5,0,Normal delivery,10.37,46.44,1.17,0
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,695.03,4.57,1,17,0,Normal delivery,14.78,185.89,4.37,0

In [471]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [472]:
deliveryMerged = pd.merge(
    finalmerge,
    all3merged,
    on="delivery_id",
    how="left"
)

In [473]:
deliveryMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,delivery_duration_hours_y,delivery_distance_km_y,fuel_cost_zar_y,customer_rating_y,attempt_number_y,delivery_hour_y,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,16.60,935.04,2504.92,2.30,3,9,6,87187.67,14531.278333,4.225000
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,1.06,57.08,115.77,3.30,1,12,9,556943.59,61882.621111,3.161111
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,7.56,402.48,891.87,4.09,1,19,12,682047.43,56837.285833,6.170833
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,3.35,147.70,609.51,3.68,1,16,14,364405.93,26028.995000,6.772857
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,1.81,54.77,122.58,4.18,1,17,11,242469.29,22042.662727,13.041818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,1.33,64.93,202.73,4.04,1,6,13,513060.49,39466.191538,7.640769
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,3.63,261.61,946.81,4.29,2,16,13,945833.66,72756.435385,4.793846
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,2.01,100.67,371.75,4.38,1,13,16,693765.03,43360.314375,6.315000
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,1.17,58.36,157.25,4.64,1,5,18,393822.40,21879.022222,6.840000
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,4.37,217.80,695.03,4.57,1,17,8,55380.60,6922.575000,9.558750

In [474]:
lastMerged = deliveryMerged.merge(deliveries_cleaned)

In [475]:
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [476]:
lastMerged['customer_average_distance'] = (
lastMerged.groupby('customer_id_x')['delivery_distance_km']
.transform('mean')
)
lastMerged["distance_vs_average"] =(lastMerged["delivery_distance_km"] / lastMerged["customer_average_distance"])
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1,230.100000,4.063625
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,Delivered,1.06,57.08,115.77,3.30,1,12,5,152.032222,0.375447
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,Delivered,7.56,402.48,891.87,4.09,1,19,4,338.757500,1.188107
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,Delivered,3.35,147.70,609.51,3.68,1,16,1,380.225000,0.388454
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,Delivered,1.81,54.77,122.58,4.18,1,17,2,759.037273,0.072157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,Delivered,1.33,64.93,202.73,4.04,1,6,1,429.092308,0.151319
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,Delivered,3.63,261.61,946.81,4.29,2,16,1,275.552308,0.949402
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,Delivered,2.01,100.67,371.75,4.38,1,13,2,336.391250,0.299265
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,Delivered,1.17,58.36,157.25,4.64,1,5,2,381.967222,0.152788
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,Delivered,4.37,217.80,695.03,4.57,1,17,5,534.656250,0.407365

In [477]:
lastMerged['delivery_delay_hours'] = (
lastMerged.groupby('delivery_distance_km')['delivery_duration_hours']
.transform('mean')
)
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average,delivery_delay_hours
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,16.60,935.04,2504.92,2.30,3,9,1,230.100000,4.063625,16.386667
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,1.06,57.08,115.77,3.30,1,12,5,152.032222,0.375447,1.462500
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,7.56,402.48,891.87,4.09,1,19,4,338.757500,1.188107,7.364286
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,3.35,147.70,609.51,3.68,1,16,1,380.225000,0.388454,3.099524
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,1.81,54.77,122.58,4.18,1,17,2,759.037273,0.072157,1.558125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,1.33,64.93,202.73,4.04,1,6,1,429.092308,0.151319,1.694063
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,3.63,261.61,946.81,4.29,2,16,1,275.552308,0.949402,4.885556
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,2.01,100.67,371.75,4.38,1,13,2,336.391250,0.299265,2.194324
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,1.17,58.36,157.25,4.64,1,5,2,381.967222,0.152788,1.700556
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,4.37,217.80,695.03,4.57,1,17,5,534.656250,0.407365,4.063077

In [478]:
lastMerged['late_delivery_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [479]:
lastMerged['long_distance_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('mean')
)

In [480]:
lastMerged['repeat_delay_flag'] = (
lastMerged.groupby('attempt_number')['delivery_duration_hours']
.transform('count')
)
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average,delivery_delay_hours,long_distance_flag,repeat_delay_flag
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2504.92,2.30,3,9,1,230.100000,4.063625,16.386667,16.60,15384
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,115.77,3.30,1,12,5,152.032222,0.375447,1.462500,1.06,888559
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,891.87,4.09,1,19,4,338.757500,1.188107,7.364286,7.56,888559
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,609.51,3.68,1,16,1,380.225000,0.388454,3.099524,3.35,888559
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,122.58,4.18,1,17,2,759.037273,0.072157,1.558125,1.81,888559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,202.73,4.04,1,6,1,429.092308,0.151319,1.694063,1.33,888559
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,946.81,4.29,2,16,1,275.552308,0.949402,4.885556,3.63,96057
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,371.75,4.38,1,13,2,336.391250,0.299265,2.194324,2.01,888559
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,157.25,4.64,1,5,2,381.967222,0.152788,1.700556,1.17,888559
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,695.03,4.57,1,17,5,534.656250,0.407365,4.063077,4.37,888559

In [481]:
#lastMerged[["delivery_id","delivery_hour", "delivery_weekday", "customer_shipment_count", "customer_average_delivery_time", "distance_vs_average", "delivery_delay_hours", "late_delivery_flag", "long_distance_flag", "repeat_delay_flag"]].drop_duplicates().merge(deliveries_cleaned).to_csv("final_data/deliveries_final.csv", index=False)

# DELIVERY DATE FEATURE (DATE FEATURES:)

In [482]:
#Converting object to datetime
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [483]:
deliveries_cleaned["year"] = deliveries_cleaned["delivery_date"].dt.year

In [484]:
deliveries_cleaned["month"] = deliveries_cleaned["delivery_date"].dt.month

In [485]:
deliveries_cleaned["day"] = deliveries_cleaned["delivery_date"].dt.day

In [486]:
deliveries_cleaned["weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [487]:
deliveries_cleaned["hour"] = deliveries_cleaned["delivery_hour"]

In [488]:
deliveries_cleaned["is_weekend"] = deliveries_cleaned["weekday"] >= 5

In [489]:
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,year,month,day,weekday,hour,is_weekend
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1,2025,12,16,1,9,False
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5,2025,3,22,5,12,True
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4,2026,6,26,4,19,False
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1,2026,7,21,1,16,False
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2,2025,7,16,2,17,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1,2025,7,8,1,6,False
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1,2026,5,5,1,16,False
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2,2025,12,17,2,13,False
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2,2026,3,4,2,5,False
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5,2025,5,31,5,17,True

In [490]:
#deliveries_cleaned.to_csv("features_engineering/deliveries_date_feature.csv")

# SHIPMENTS DATE FEATURE

In [491]:
#Converting object to datetime
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])

In [492]:
shipments_cleaned["year"] = shipments_cleaned["shipment_date"].dt.year
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025
...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025

In [493]:
shipments_cleaned["month"] = shipments_cleaned["shipment_date"].dt.month
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5

In [494]:
shipments_cleaned["day"] = shipments_cleaned["shipment_date"].dt.day
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30

In [495]:
shipments_cleaned["weekday"] = shipments_cleaned["shipment_date"].dt.weekday
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4

In [496]:
# shipments_cleaned["hour"] = shipments_cleaned["delivery_hour"]

In [497]:
shipments_cleaned["is_weekend"] = shipments_cleaned["weekday"] >= 5
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday,is_weekend
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6,True
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4,False
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1,False
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1,False
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4,False
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6,True
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4,False
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6,True
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4,False

In [498]:
#shipments_cleaned.to_csv("features_engineering/shipments_date_feature.csv")

# CUSTOMER DATE FEATURE

In [499]:
#Converting object to datetime
customers_cleaned.info()
customers_cleaned['registration_date'] = pd.to_datetime(customers_cleaned['registration_date'])

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   customer_id              100000 non-null  object
 1   customer_name            100000 non-null  object
 2   customer_type            100000 non-null  object
 3   province                 100000 non-null  object
 4   city                     100000 non-null  object
 5   registration_date        100000 non-null  object
 6   monthly_shipping_budget  100000 non-null  float64
dtypes: float64(1), object(6)
memory usage: 6.1+ MB

In [500]:
customers_cleaned["year"] = customers_cleaned["registration_date"].dt.year

In [501]:
customers_cleaned["month"] = customers_cleaned["registration_date"].dt.month

In [502]:
customers_cleaned["day"] = customers_cleaned["registration_date"].dt.day

In [503]:
customers_cleaned["weekday"] = customers_cleaned["registration_date"].dt.weekday

In [504]:
customers_cleaned["is_weekend"] = customers_cleaned["weekday"] >= 5
customers_cleaned

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,year,month,day,weekday,is_weekend
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,2024,10,13,6,True
1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50,2022,1,26,2,False
2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67,2019,3,4,0,False
3,C000004,Bongani Sithole,Individual,Kwazulu-Natal,Richards Bay,2021-06-30,10034.40,2021,6,30,2,False
4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38,2026,3,28,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,C099996,Dumisani Mkhize,Individual,Gauteng,Pretoria,2023-03-29,78517.63,2023,3,29,2,False
99996,C099997,Thabo Mahlangu,Individual,Western Cape,Cape Town,2023-11-08,7369.63,2023,11,8,2,False
99997,C099998,Kagiso Mthembu,Individual,Kwazulu-Natal,Newcastle,2023-04-27,9942.18,2023,4,27,3,False
99998,C099999,Thabo Maseko,Individual,Western Cape,Stellenbosch,2020-06-08,838.25,2020,6,8,0,False
99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,2019,8,31,5,True

In [505]:
#customers_cleaned.to_csv("features_engineering/customer_date_feature.csv")

In [506]:
#To access the shipment merged dataset
#data = pd.read_csv("""C:\\Users\\e1023443\\OneDrive - Sanlam Life Insurance Limited\\Desktop\\shipment_final.csv""")

In [507]:
#data

# Customer Analytics

In [508]:
customers_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   customer_id              100000 non-null  object
 1   customer_name            100000 non-null  object
 2   customer_type            100000 non-null  object
 3   province                 100000 non-null  object
 4   city                     100000 non-null  object
 5   registration_date        100000 non-null  datetime64[ns]
 6   monthly_shipping_budget  100000 non-null  float64
 7   year                     100000 non-null  int32
 8   month                    100000 non-null  int32
 9   day                      100000 non-null  int32
 10  weekday                  100000 non-null  int32
 11  is_weekend               100000 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int32(4), object(5)
memory usage: 7.7+ MB

In [509]:
#1. How many customers does the company have?
total_customers = customers_cleaned['customer_id'].nunique()
print(f"Total customers: {total_customers}")

Total customers: 100000

In [510]:
#2. Which province has the most customers?
customer_province = (
    customers_cleaned.groupby('province')['customer_id'].nunique().sort_values(ascending=False)
)
print(customer_province)
print("Province with the most customers:", customer_province.idxmax())

province
Gauteng          29867
Kwazulu-Natal    18005
Western Cape     17996
Eastern Cape     10059
Limpopo           7036
Free State        6095
Mpumalanga        5029
North West        3955
Northern Cape     1958
Name: customer_id, dtype: int64
Province with the most customers: Gauteng

In [511]:
shipping_by_segment = pd.merge(
    shipments_cleaned , 
    customers_cleaned, 
    on= "customer_id", 
    how= "left"
)
shipping_by_segment

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,...,customer_type,province,city,registration_date,monthly_shipping_budget,year_y,month_y,day_y,weekday_y,is_weekend_y
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,Individual,Northern Cape,Upington,2022-06-12,33682.40,2022,6,12,6,True
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,Individual,Gauteng,Pretoria,2019-06-02,1862.17,2019,6,2,6,True
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,Individual,Eastern Cape,Grahamstown,2019-11-25,26477.64,2019,11,25,0,False
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,Business,Mpumalanga,Nelspruit,2026-04-18,32574.97,2026,4,18,5,True
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,Business,Free State,Welkom,2019-11-10,3591.22,2019,11,10,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,Individual,Eastern Cape,Gqeberha,2022-04-22,12873.22,2022,4,22,4,False
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,Individual,Eastern Cape,Mthatha,2019-05-28,1368.66,2019,5,28,1,False
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,Individual,North West,Potchefstroom,2020-12-18,5006.93,2020,12,18,4,False
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,Individual,Gauteng,Midrand,2022-10-13,11744.83,2022,10,13,3,False
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,Business,Free State,Welkom,2024-11-12,17916.59,2024,11,12,1,False

In [512]:
#3. Which customer segment sends the most shipment?

shipments_by_segment = (
    shipping_by_segment.groupby('customer_type')['shipment_id']
    .count()
    .sort_values(ascending=False)
)

print(shipments_by_segment)
print("The customer segment with the most shipments is:", shipments_by_segment.idxmax())

customer_type
Individual    699905
Business      250102
Enterprise     49993
Name: shipment_id, dtype: int64
The customer segment with the most shipments is: Individual

In [513]:
# all3merged[["customer_id","customer_total_shipping_value"]].drop_duplicates().merge(shipments_by_segment)

In [514]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [515]:
#4. Which customer segment generate the highest shipping value?
shipping_value = (all3merged.groupby('customer_type')['customer_total_shipping_value'].sum().sort_values(ascending=False))
print(shipping_value)
print("The most customer shipping segment:", shipping_value.idxmax())

customer_type
Individual    2.400271e+11
Business      8.600146e+10
Enterprise    1.728869e+10
Name: customer_total_shipping_value, dtype: float64
The most customer shipping segment: Individual

In [516]:
#5. Which customer have the highest shipment frequency? 
frequent_ship = all3merged.groupby("customer_name").agg(frequent_ship=("shipment_id","count"))
frequent_ship.reset_index()
frequent_ship.sort_values(by='frequent_ship', ascending=False).head(10)

                   frequent_ship
customer_name
Mpho Williams               2068
Precious Moyo               2062
Siyabonga Mthembu           2014
Bongani Mkhize              1995
Amanda Mthembu              1979
Tshepo Dlamini              1976
Tshepo Williams             1970
Phumzile Jacobs             1967
Thabo Moyo                  1962
Karabo Dlamini              1960

In [517]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [518]:
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [519]:
# #6. Which customer experienced the most delayed deliveries? 
late_deliveries = finalmerge[finalmerge["delivery_status"] == "Delayed"]

deliveries = late_deliveries.groupby("customer_id").agg(
    deliveries=("delivery_status", "count")
)

deliveries.reset_index()
deliveries.sort_values(by='deliveries', ascending=False).head(10)

             deliveries
customer_id
C097972               6
C039665               5
C065659               5
C088313               5
C089637               5
C010211               4
C048350               4
C049297               4
C027552               4
C036807               4

In [520]:
import matplotlib.pyplot as plt 

#Create a

# Shipment Analytics

In [521]:
#7. Which shipment types are most common? 
shipment_count = (
    shipments_cleaned.groupby('shipment_type')['customer_id'].nunique().sort_values(ascending=False)
)
print(shipment_count)
print("Shipment type that are most common:", shipment_count.idxmax())

shipment_type
Standard         99342
Express          86389
Bulk             77567
Same Day         63278
International    39443
Name: customer_id, dtype: int64
Shipment type that are most common: Standard

In [522]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [523]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")

In [524]:
delship = pd.merge(
    deliveries_cleaned,
    shipments_cleaned,
    on="shipment_id",
    how="left"
)

In [525]:
#8. Which delivery method are most frequently used? 
frequent_delivery = delship.groupby("delivery_method").agg(frequent_delivery=("delivery_id","count"))
frequent_delivery.reset_index()
frequent_delivery.sort_values(by='frequent_delivery', ascending=False)

                 frequent_delivery
delivery_method
Road                        649700
Courier                     150167
Air                         100143
Freight                      99990

In [526]:
cust = delship.merge(customers_cleaned)
cust

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,...,weight_kg,declared_value_zar,distance_km,priority,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,...,11.97,10832.99,926.17,Low,Zanele Adams,Individual,Northern Cape,Upington,2022-06-12,33682.40
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,...,73.29,90025.97,63.22,Medium,Nomsa Cele,Individual,Gauteng,Pretoria,2019-06-02,1862.17
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,...,90.70,73339.17,374.86,Critical,Nomsa Molefe,Individual,Eastern Cape,Grahamstown,2019-11-25,26477.64
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,...,13.26,11410.73,148.44,Medium,Ayanda Naidoo,Business,Mpumalanga,Nelspruit,2026-04-18,32574.97
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,...,36.98,23529.59,61.17,Low,Nandi Molefe,Business,Free State,Welkom,2019-11-10,3591.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,...,5.33,6355.05,59.99,Medium,Sibusiso Nkosi,Individual,Eastern Cape,Gqeberha,2022-04-22,12873.22
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,...,7.11,9506.09,235.68,Medium,Tshepo Botha,Individual,Eastern Cape,Mthatha,2019-05-28,1368.66
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,...,12.26,3713.83,100.23,Low,Amanda Zulu,Individual,North West,Potchefstroom,2020-12-18,5006.93
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,...,10.37,14523.73,46.44,High,Tshepo Mkhize,Individual,Gauteng,Midrand,2022-10-13,11744.83
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,...,14.78,11580.34,185.89,Medium,Busisiwe Van Wyk,Business,Free State,Welkom,2024-11-12,17916.59

In [527]:
#9. Which province generates the most shipment volume?
province = cust.groupby("province").agg(frequent_delivery=("shipment_id","count"))
province.reset_index()
province.sort_values(by='province', ascending=False)

               frequent_delivery
province
Western Cape              179668
Northern Cape              19434
North West                 39820
Mpumalanga                 50195
Limpopo                    70324
Kwazulu-Natal             180474
Gauteng                   298437
Free State                 60669
Eastern Cape              100979

In [ ]:
#10. What are the busiest shipping days?
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])
busiest_days = shipments_cleaned['shipment_date'].dt.day_name().value_counts()
print(busiest_days)

In [ ]:
#11. How does shipment activity change over time?
cust['registration_date'] = pd.to_datetime(cust['registration_date'])
shipment_activity = (
cust.groupby(cust['registration_date'].dt.to_period('M'))
.agg(total_shipments=('shipment_id', 'count')).head(10)#.tail(10)
.reset_index())
print(shipment_activity)

In [ ]:
#cust.columns