# Customer Feature Engineering

In [75]:
import pandas as pd
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [76]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [77]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [78]:
#Merging datasets (customers & shipments)
mergedcusship = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [79]:
all3merged = mergedcusship.merge(deliveries_cleaned)

In [80]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,D009146,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,D009897,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,D002742,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,D004317,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,D005469,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,D007343,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,D005723,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,D000789,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,D007516,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,D009458,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6

In [81]:
#Customer shipment count
all3merged['customer_shipment_count'] = (
all3merged.groupby('customer_id')['shipment_id']
.transform('count')
)

In [82]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6

In [83]:
#Creating customer total shipments
all3merged['customer_total_shipping_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'] 
.transform('sum')
)

In [84]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31

In [85]:
#Creating customer average shipment
all3merged['customer_average_shipment_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'].
transform('mean')
)

In [86]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667

In [87]:
all3merged['customer_average_delivery_time'] = (
all3merged.groupby('customer_id')['delivery_duration_hours']
.transform('mean')
)

In [88]:
#All 4 features
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [89]:
all3merged.to_csv("features_engineering/customers_feature.csv")

In [117]:
all3merged[["customer_id","customer_shipment_count","customer_total_shipping_value","customer_average_shipment_value","customer_average_delivery_time"]].drop_duplicates().merge(customers_cleaned).to_csv("customer_final.csv")

In [ ]:
all3merged[["shipment_id","shipment_weight","shipment_distance","delivery_duration","late_delivery_flag"]].drop_duplicates().merge(shipments_cleaned).to_csv("shipment_final.csv")

# DELIVERY DATE FEATURE (DATE FEATURES:)

In [91]:
#Converting object to datetime
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [92]:
deliveries_cleaned["year"] = deliveries_cleaned["delivery_date"].dt.year

In [93]:
deliveries_cleaned["month"] = deliveries_cleaned["delivery_date"].dt.month

In [94]:
deliveries_cleaned["day"] = deliveries_cleaned["delivery_date"].dt.day

In [95]:
deliveries_cleaned["weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [96]:
deliveries_cleaned["hour"] = deliveries_cleaned["delivery_hour"]

In [97]:
deliveries_cleaned["is_weekend"] = deliveries_cleaned["weekday"] >= 5

In [98]:
deliveries_cleaned

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,year,month,day,weekday,hour,is_weekend
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,2025,12,16,1,9,False
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,2025,3,22,5,12,True
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,2026,6,26,4,19,False
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,2026,7,21,1,16,False
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2025,7,16,2,17,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,2025,7,8,1,6,False
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,2026,5,5,1,16,False
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2025,12,17,2,13,False
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2026,3,4,2,5,False
999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,2025,5,31,5,17,True

In [99]:
deliveries_cleaned.to_csv("features_engineering/deliveries_date_feature.csv")

# SHIPMENTS DATE FEATURE

In [100]:
#Converting object to datetime
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])

In [101]:
shipments_cleaned["year"] = shipments_cleaned["shipment_date"].dt.year
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025
...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025

In [102]:
shipments_cleaned["month"] = shipments_cleaned["shipment_date"].dt.month
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5

In [103]:
shipments_cleaned["day"] = shipments_cleaned["shipment_date"].dt.day
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30

In [104]:
shipments_cleaned["weekday"] = shipments_cleaned["shipment_date"].dt.weekday
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4

In [105]:
# shipments_cleaned["hour"] = shipments_cleaned["delivery_hour"]

In [106]:
shipments_cleaned["is_weekend"] = shipments_cleaned["weekday"] >= 5
shipments_cleaned

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday,is_weekend
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6,True
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4,False
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1,False
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1,False
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4,False
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6,True
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4,False
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6,True
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4,False

In [107]:
shipments_cleaned.to_csv("features_engineering/shipments_date_feature.csv")

# CUSTOMER DATE FEATURE

In [108]:
#Converting object to datetime
customers_cleaned.info()
customers_cleaned['registration_date'] = pd.to_datetime(customers_cleaned['registration_date'])

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   customer_id              100000 non-null  object
 1   customer_name            100000 non-null  object
 2   customer_type            100000 non-null  object
 3   province                 100000 non-null  object
 4   city                     100000 non-null  object
 5   registration_date        100000 non-null  object
 6   monthly_shipping_budget  100000 non-null  float64
dtypes: float64(1), object(6)
memory usage: 6.1+ MB

In [109]:
customers_cleaned["year"] = customers_cleaned["registration_date"].dt.year

In [110]:
customers_cleaned["month"] = customers_cleaned["registration_date"].dt.month

In [111]:
customers_cleaned["day"] = customers_cleaned["registration_date"].dt.day

In [112]:
customers_cleaned["weekday"] = customers_cleaned["registration_date"].dt.weekday

In [113]:
customers_cleaned["is_weekend"] = customers_cleaned["weekday"] >= 5
customers_cleaned

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,year,month,day,weekday,is_weekend
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,2024,10,13,6,True
1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50,2022,1,26,2,False
2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67,2019,3,4,0,False
3,C000004,Bongani Sithole,Individual,Kwazulu-Natal,Richards Bay,2021-06-30,10034.40,2021,6,30,2,False
4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38,2026,3,28,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,C099996,Dumisani Mkhize,Individual,Gauteng,Pretoria,2023-03-29,78517.63,2023,3,29,2,False
99996,C099997,Thabo Mahlangu,Individual,Western Cape,Cape Town,2023-11-08,7369.63,2023,11,8,2,False
99997,C099998,Kagiso Mthembu,Individual,Kwazulu-Natal,Newcastle,2023-04-27,9942.18,2023,4,27,3,False
99998,C099999,Thabo Maseko,Individual,Western Cape,Stellenbosch,2020-06-08,838.25,2020,6,8,0,False
99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,2019,8,31,5,True

In [114]:
customers_cleaned.to_csv("features_engineering/customer_date_feature.csv")