# Customer Feature Engineering

In [221]:
import pandas as pd
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [222]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [223]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [224]:
#Merging datasets (customers & shipments)
mergedcusship = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [225]:
all3merged = mergedcusship.merge(deliveries_cleaned)

In [226]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,D009146,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,D009897,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,D002742,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,D004317,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,D005469,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,D007343,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,D005723,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,D000789,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,D007516,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,D009458,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6

In [227]:
#Customer shipment count
all3merged['customer_shipment_count'] = (
all3merged.groupby('customer_id')['shipment_id']
.transform('count')
)

In [228]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6

In [229]:
#Creating customer total shipments
all3merged['customer_total_shipping_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'] 
.transform('sum')
)

In [230]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31

In [231]:
#Creating customer average shipment
all3merged['customer_average_shipment_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'].
transform('mean')
)

In [232]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667

In [233]:
all3merged['customer_average_delivery_time'] = (
all3merged.groupby('customer_id')['delivery_duration_hours']
.transform('mean')
)

In [234]:
#All 4 features
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [235]:
all3merged[["customer_id","customer_shipment_count","customer_total_shipping_value","customer_average_shipment_value","customer_average_delivery_time"]].drop_duplicates().merge(customers_cleaned).to_csv("final_data/customer_final.csv")

# Shipment Features

In [236]:
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [237]:
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [238]:
delivery_labels_cleaned = pd.read_csv("cleaned_supplyguard_data/delivery_labels_cleaned.csv")
delivery_labels_cleaned

        Unnamed: 0  delivery_id  is_late             risk_reason
0                0  DL000000001        1  Long delivery distance
1                1  DL000000002        0         Normal delivery
2                2  DL000000003        0         Normal delivery
3                3  DL000000004        0         Normal delivery
4                4  DL000000005        0         Normal delivery
...            ...          ...      ...                     ...
999995      999995  DL000999996        0         Normal delivery
999996      999996  DL000999997        0         Normal delivery
999997      999997  DL000999998        0         Normal delivery
999998      999998  DL000999999        0         Normal delivery
999999      999999  DL001000000        0         Normal delivery

[1000000 rows x 4 columns]

In [239]:
shipdeliv = pd.merge(
    shipments_cleaned,
    deliveries_cleaned,
    on="shipment_id",
    how="left"
)

In [240]:
shipdeliv

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [241]:
finalmerge = shipdeliv.merge(delivery_labels_cleaned)

In [242]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,Delivered Late,16.60,935.04,2504.92,2.30,3,9,0,1,Long delivery distance
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,Delivered,1.06,57.08,115.77,3.30,1,12,1,0,Normal delivery
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,Delivered,7.56,402.48,891.87,4.09,1,19,2,0,Normal delivery
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,Delivered,3.35,147.70,609.51,3.68,1,16,3,0,Normal delivery
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,Delivered,1.81,54.77,122.58,4.18,1,17,4,0,Normal delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,Delivered,1.33,64.93,202.73,4.04,1,6,999995,0,Normal delivery
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,Delivered,3.63,261.61,946.81,4.29,2,16,999996,0,Normal delivery
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,Delivered,2.01,100.67,371.75,4.38,1,13,999997,0,Normal delivery
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,Delivered,1.17,58.36,157.25,4.64,1,5,999998,0,Normal delivery
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,Delivered,4.37,217.80,695.03,4.57,1,17,999999,0,Normal delivery

In [243]:
finalmerge['shipment_weight'] = (
finalmerge.groupby('shipment_id')['weight_kg']
.transform('sum')
)

In [244]:
finalmerge['shipment_distance'] = (
finalmerge.groupby('shipment_id')['distance_km']
.transform('sum')
)

In [245]:
finalmerge['delivery_duration'] = (
finalmerge.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [246]:
finalmerge['late_delivery_flag'] = (
finalmerge.groupby('delivery_id')['is_late']
.transform('sum')
)

In [247]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,2.30,3,9,0,1,Long delivery distance,11.97,926.17,16.60,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,3.30,1,12,1,0,Normal delivery,73.29,63.22,1.06,0
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,4.09,1,19,2,0,Normal delivery,90.70,374.86,7.56,0
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.68,1,16,3,0,Normal delivery,13.26,148.44,3.35,0
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,4.18,1,17,4,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,4.04,1,6,999995,0,Normal delivery,5.33,59.99,1.33,0
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,4.29,2,16,999996,0,Normal delivery,7.11,235.68,3.63,0
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,4.38,1,13,999997,0,Normal delivery,12.26,100.23,2.01,0
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,4.64,1,5,999998,0,Normal delivery,10.37,46.44,1.17,0
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.57,1,17,999999,0,Normal delivery,14.78,185.89,4.37,0

In [ ]:
#finalmerge[["shipment_id","shipment_weight","shipment_distance","delivery_duration","late_delivery_flag"]].drop_duplicates().merge(shipments_cleaned).to_csv("final_data/shipment_final.csv", index=False)

# Delivery Feature Engineering

In [249]:
import pandas as pd
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [250]:
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [251]:
deliveries_cleaned["delivery_weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [252]:
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [253]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,2.30,3,9,0,1,Long delivery distance,11.97,926.17,16.60,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,3.30,1,12,1,0,Normal delivery,73.29,63.22,1.06,0
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,4.09,1,19,2,0,Normal delivery,90.70,374.86,7.56,0
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.68,1,16,3,0,Normal delivery,13.26,148.44,3.35,0
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,4.18,1,17,4,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,4.04,1,6,999995,0,Normal delivery,5.33,59.99,1.33,0
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,4.29,2,16,999996,0,Normal delivery,7.11,235.68,3.63,0
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,4.38,1,13,999997,0,Normal delivery,12.26,100.23,2.01,0
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,4.64,1,5,999998,0,Normal delivery,10.37,46.44,1.17,0
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.57,1,17,999999,0,Normal delivery,14.78,185.89,4.37,0

In [254]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [255]:
deliveryMerged = pd.merge(
    finalmerge,
    all3merged,
    on="delivery_id",
    how="left"
)

In [256]:
deliveryMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,delivery_duration_hours_y,delivery_distance_km_y,fuel_cost_zar_y,customer_rating_y,attempt_number_y,delivery_hour_y,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,16.60,935.04,2504.92,2.30,3,9,6,87187.67,14531.278333,4.225000
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,1.06,57.08,115.77,3.30,1,12,9,556943.59,61882.621111,3.161111
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,7.56,402.48,891.87,4.09,1,19,12,682047.43,56837.285833,6.170833
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.35,147.70,609.51,3.68,1,16,14,364405.93,26028.995000,6.772857
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,1.81,54.77,122.58,4.18,1,17,11,242469.29,22042.662727,13.041818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,1.33,64.93,202.73,4.04,1,6,13,513060.49,39466.191538,7.640769
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,3.63,261.61,946.81,4.29,2,16,13,945833.66,72756.435385,4.793846
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,2.01,100.67,371.75,4.38,1,13,16,693765.03,43360.314375,6.315000
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,1.17,58.36,157.25,4.64,1,5,18,393822.40,21879.022222,6.840000
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.37,217.80,695.03,4.57,1,17,8,55380.60,6922.575000,9.558750

In [257]:
lastMerged = deliveryMerged.merge(deliveries_cleaned)

In [258]:
lastMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [ ]:
lastMerged['customer_average_distance'] = (
lastMerged.groupby('customer_id_x')['delivery_distance_km']
.transform('mean')
)
lastMerged["distance_vs_average"] =(lastMerged["delivery_distance_km"] / lastMerged["customer_average_distance"])
lastMerged

In [ ]:
lastMerged['delivery_delay_hours'] = (
lastMerged.groupby('delivery_distance_km')['delivery_duration_hours']
.transform('mean')
)
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,distance_vs_average,customer_average_distancs,delivery_delay_hours
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,16.60,935.04,2504.92,2.30,3,9,1,4.063625,230.100000,16.386667
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,1.06,57.08,115.77,3.30,1,12,5,0.375447,152.032222,1.462500
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,7.56,402.48,891.87,4.09,1,19,4,1.188107,338.757500,7.364286
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,3.35,147.70,609.51,3.68,1,16,1,0.388454,380.225000,3.099524
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,1.81,54.77,122.58,4.18,1,17,2,0.072157,759.037273,1.558125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,1.33,64.93,202.73,4.04,1,6,1,0.151319,429.092308,1.694063
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,3.63,261.61,946.81,4.29,2,16,1,0.949402,275.552308,4.885556
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,2.01,100.67,371.75,4.38,1,13,2,0.299265,336.391250,2.194324
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,1.17,58.36,157.25,4.64,1,5,2,0.152788,381.967222,1.700556
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,4.37,217.80,695.03,4.57,1,17,5,0.407365,534.656250,4.063077

In [ ]:
lastMerged['late_delivery_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [ ]:
lastMerged['long_distance_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('mean')
)

In [ ]:
lastMerged['repeat_delay_flag'] = (
lastMerged.groupby('attempt_number')['delivery_duration_hours']
.transform('count')
)
lastMerged

,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,priority_x,...,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,distance_vs_average,customer_average_distancs,delivery_delay_hours,long_distance_flag,repeat_delay_flag
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,...,2504.92,2.30,3,9,1,4.063625,230.100000,16.386667,16.60,15384
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,...,115.77,3.30,1,12,5,0.375447,152.032222,1.462500,1.06,888559
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,...,891.87,4.09,1,19,4,1.188107,338.757500,7.364286,7.56,888559
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,...,609.51,3.68,1,16,1,0.388454,380.225000,3.099524,3.35,888559
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,...,122.58,4.18,1,17,2,0.072157,759.037273,1.558125,1.81,888559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,...,202.73,4.04,1,6,1,0.151319,429.092308,1.694063,1.33,888559
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,...,946.81,4.29,2,16,1,0.949402,275.552308,4.885556,3.63,96057
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,...,371.75,4.38,1,13,2,0.299265,336.391250,2.194324,2.01,888559
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,...,157.25,4.64,1,5,2,0.152788,381.967222,1.700556,1.17,888559
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,...,695.03,4.57,1,17,5,0.407365,534.656250,4.063077,4.37,888559

In [ ]:
#lastMerged[["delivery_id","delivery_hour", "delivery_weekday", "customer_shipment_count", "customer_average_delivery_time", "distance_vs_average", "delivery_delay_hours", "late_delivery_flag", "long_distance_flag", "repeat_delay_flag"]].drop_duplicates().merge(deliveries_cleaned).to_csv("final_data/deliveries_final.csv", index=False)

# DELIVERY DATE FEATURE (DATE FEATURES:)

In [ ]:
#Converting object to datetime
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [ ]:
deliveries_cleaned["year"] = deliveries_cleaned["delivery_date"].dt.year

In [ ]:
deliveries_cleaned["month"] = deliveries_cleaned["delivery_date"].dt.month

In [ ]:
deliveries_cleaned["day"] = deliveries_cleaned["delivery_date"].dt.day

In [ ]:
deliveries_cleaned["weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [ ]:
deliveries_cleaned["hour"] = deliveries_cleaned["delivery_hour"]

In [ ]:
deliveries_cleaned["is_weekend"] = deliveries_cleaned["weekday"] >= 5

In [ ]:
deliveries_cleaned

        Unnamed: 0  delivery_id shipment_id driver_id vehicle_id  \
0                0  DL000000001  S000000001   D002400    V013743
1                1  DL000000002  S000000002   D006019    V012835
2                2  DL000000003  S000000003   D006461    V000347
3                3  DL000000004  S000000004   D007914    V010330
4                4  DL000000005  S000000005   D005693    V011795
...            ...          ...         ...       ...        ...
999995      999995  DL000999996  S000999996   D005627    V000427
999996      999996  DL000999997  S000999997   D001882    V006763
999997      999997  DL000999998  S000999998   D008550    V010821
999998      999998  DL000999999  S000999999   D008389    V004063
999999      999999  DL001000000  S001000000   D005538    V011867

       delivery_date delivery_status  delivery_duration_hours  \
0         2025-12-16  Delivered Late                    16.60
1         2025-03-22       Delivered                     1.06
2         2026-06-26       Delivered                     7.56
3         2026-07-21       Delivered                     3.35
4         2025-07-16       Delivered                     1.81
...              ...             ...                      ...
999995    2025-07-08       Delivered                     1.33
999996    2026-05-05       Delivered                     3.63
999997    2025-12-17       Delivered                     2.01
999998    2026-03-04       Delivered                     1.17
999999    2025-05-31       Delivered                     4.37

        fuel_cost_zar  customer_rating  attempt_number  delivery_hour  \
0             2504.92             2.30               3              9
1              115.77             3.30               1             12
2              891.87             4.09               1             19
3              609.51             3.68               1             16
4              122.58             4.18               1             17
...               ...              ...             ...            ...
999995         202.73             4.04               1              6
999996         946.81             4.29               2             16
999997         371.75             4.38               1             13
999998         157.25             4.64               1              5
999999         695.03             4.57               1             17

        delivery_weekday  year  month  day  weekday  hour  is_weekend
0                      1  2025     12   16        1     9       False
1                      5  2025      3   22        5    12        True
2                      4  2026      6   26        4    19       False
3                      1  2026      7   21        1    16       False
4                      2  2025      7   16        2    17       False
...                  ...   ...    ...  ...      ...   ...         ...
999995                 1  2025      7    8        1     6       False
999996                 1  2026      5    5        1    16       False
999997                 2  2025     12   17        2    13       False
999998                 2  2026      3    4        2     5       False
999999                 5  2025      5   31        5    17        True

[1000000 rows x 19 columns]

In [ ]:
#deliveries_cleaned.to_csv("features_engineering/deliveries_date_feature.csv")

# SHIPMENTS DATE FEATURE

In [ ]:
#Converting object to datetime
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])

In [ ]:
shipments_cleaned["year"] = shipments_cleaned["shipment_date"].dt.year
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025

In [ ]:
shipments_cleaned["month"] = shipments_cleaned["shipment_date"].dt.month
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5

In [ ]:
shipments_cleaned["day"] = shipments_cleaned["shipment_date"].dt.day
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30

In [ ]:
shipments_cleaned["weekday"] = shipments_cleaned["shipment_date"].dt.weekday
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4

In [ ]:
# shipments_cleaned["hour"] = shipments_cleaned["delivery_hour"]

In [ ]:
shipments_cleaned["is_weekend"] = shipments_cleaned["weekday"] >= 5
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday,is_weekend
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6,True
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4,False
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1,False
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1,False
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4,False
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6,True
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4,False
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6,True
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4,False

In [ ]:
#shipments_cleaned.to_csv("features_engineering/shipments_date_feature.csv")

# CUSTOMER DATE FEATURE

In [ ]:
#Converting object to datetime
customers_cleaned.info()
customers_cleaned['registration_date'] = pd.to_datetime(customers_cleaned['registration_date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Unnamed: 0               100000 non-null  int64
 1   customer_id              100000 non-null  object
 2   customer_name            100000 non-null  object
 3   customer_type            100000 non-null  object
 4   province                 100000 non-null  object
 5   city                     100000 non-null  object
 6   registration_date        100000 non-null  object
 7   monthly_shipping_budget  100000 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.1+ MB

In [ ]:
customers_cleaned["year"] = customers_cleaned["registration_date"].dt.year

In [ ]:
customers_cleaned["month"] = customers_cleaned["registration_date"].dt.month

In [ ]:
customers_cleaned["day"] = customers_cleaned["registration_date"].dt.day

In [ ]:
customers_cleaned["weekday"] = customers_cleaned["registration_date"].dt.weekday

In [ ]:
customers_cleaned["is_weekend"] = customers_cleaned["weekday"] >= 5
customers_cleaned

,Unnamed: 0,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,year,month,day,weekday,is_weekend
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,2024,10,13,6,True
1,1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50,2022,1,26,2,False
2,2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67,2019,3,4,0,False
3,3,C000004,Bongani Sithole,Individual,Kwazulu-Natal,Richards Bay,2021-06-30,10034.40,2021,6,30,2,False
4,4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38,2026,3,28,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,C099996,Dumisani Mkhize,Individual,Gauteng,Pretoria,2023-03-29,78517.63,2023,3,29,2,False
99996,99996,C099997,Thabo Mahlangu,Individual,Western Cape,Cape Town,2023-11-08,7369.63,2023,11,8,2,False
99997,99997,C099998,Kagiso Mthembu,Individual,Kwazulu-Natal,Newcastle,2023-04-27,9942.18,2023,4,27,3,False
99998,99998,C099999,Thabo Maseko,Individual,Western Cape,Stellenbosch,2020-06-08,838.25,2020,6,8,0,False
99999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,2019,8,31,5,True

In [ ]:
#customers_cleaned.to_csv("features_engineering/customer_date_feature.csv")

In [ ]:
#To access the shipment merged dataset
#data = pd.read_csv("""C:\\Users\\e1023443\\OneDrive - Sanlam Life Insurance Limited\\Desktop\\shipment_final.csv""")

In [ ]:
#data

,Unnamed: 0.1,shipment_id,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag,Unnamed: 0,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,0,S000000001,11.97,926.17,16.60,1,0,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,1,S000000002,73.29,63.22,1.06,0,1,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,2,S000000003,90.70,374.86,7.56,0,2,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,3,S000000004,13.26,148.44,3.35,0,3,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,4,S000000005,36.98,61.17,1.81,0,4,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,5.33,59.99,1.33,0,999995,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,999996,S000999997,7.11,235.68,3.63,0,999996,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,999997,S000999998,12.26,100.23,2.01,0,999997,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,999998,S000999999,10.37,46.44,1.17,0,999998,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,999999,S001000000,14.78,185.89,4.37,0,999999,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium