# Customer Feature Engineering

In [2]:
import pandas as pd
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [3]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [4]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [5]:
#Merging datasets (customers & shipments)
mergedcusship = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [6]:
all3merged = mergedcusship.merge(deliveries_cleaned)

In [7]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,D009146,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,D009897,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,D002742,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,D004317,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,D005469,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,D007343,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,D005723,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,D000789,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,D007516,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,D009458,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6

In [8]:
#Customer shipment count
all3merged['customer_shipment_count'] = (
all3merged.groupby('customer_id')['shipment_id']
.transform('count')
)

In [9]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,V013306,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,V004861,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,V002447,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,V000024,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,V000060,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,V013961,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,V005372,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,V001243,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,V003396,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,V003069,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6

In [10]:
#Creating customer total shipments
all3merged['customer_total_shipping_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'] 
.transform('sum')
)

In [11]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,2026-07-25,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,2025-06-21,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,2026-01-30,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2025-09-27,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,2025-09-28,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,2026-04-21,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,2026-04-14,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2025-11-04,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,2025-10-23,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,2025-07-29,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31

In [12]:
#Creating customer average shipment
all3merged['customer_average_shipment_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'].
transform('mean')
)

In [13]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,Delivered,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,Delivered,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,Delivered Late,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,Delivered,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,Delivered,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,Delivered,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,Delivered,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,Delivered,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,Delivered,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,Delivered,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667

In [14]:
all3merged['customer_average_delivery_time'] = (
all3merged.groupby('customer_id')['delivery_duration_hours']
.transform('mean')
)

In [15]:
#All 4 features
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [16]:
#all3merged[["customer_id","customer_shipment_count","customer_total_shipping_value","customer_average_shipment_value","customer_average_delivery_time"]].drop_duplicates().merge(customers_cleaned).to_csv("final_data/customer_final.csv")

# Shipment Features

In [17]:
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [18]:
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [19]:
delivery_labels_cleaned = pd.read_csv("cleaned_supplyguard_data/delivery_labels_cleaned.csv")
#delivery_labels_cleaned

        Unnamed: 0  delivery_id  is_late             risk_reason
0                0  DL000000001        1  Long delivery distance
1                1  DL000000002        0         Normal delivery
2                2  DL000000003        0         Normal delivery
3                3  DL000000004        0         Normal delivery
4                4  DL000000005        0         Normal delivery
...            ...          ...      ...                     ...
999995      999995  DL000999996        0         Normal delivery
999996      999996  DL000999997        0         Normal delivery
999997      999997  DL000999998        0         Normal delivery
999998      999998  DL000999999        0         Normal delivery
999999      999999  DL001000000        0         Normal delivery

[1000000 rows x 4 columns]

In [20]:
shipdeliv = pd.merge(
    shipments_cleaned,
    deliveries_cleaned,
    on="shipment_id",
    how="left"
)

In [21]:
shipdeliv

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17

In [22]:
finalmerge = shipdeliv.merge(delivery_labels_cleaned)

In [23]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,Delivered Late,16.60,935.04,2504.92,2.30,3,9,0,1,Long delivery distance
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,Delivered,1.06,57.08,115.77,3.30,1,12,1,0,Normal delivery
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,Delivered,7.56,402.48,891.87,4.09,1,19,2,0,Normal delivery
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,Delivered,3.35,147.70,609.51,3.68,1,16,3,0,Normal delivery
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,Delivered,1.81,54.77,122.58,4.18,1,17,4,0,Normal delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,Delivered,1.33,64.93,202.73,4.04,1,6,999995,0,Normal delivery
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,Delivered,3.63,261.61,946.81,4.29,2,16,999996,0,Normal delivery
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,Delivered,2.01,100.67,371.75,4.38,1,13,999997,0,Normal delivery
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,Delivered,1.17,58.36,157.25,4.64,1,5,999998,0,Normal delivery
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,Delivered,4.37,217.80,695.03,4.57,1,17,999999,0,Normal delivery

In [24]:
finalmerge['shipment_weight'] = (
finalmerge.groupby('shipment_id')['weight_kg']
.transform('sum')
)

In [25]:
finalmerge['shipment_distance'] = (
finalmerge.groupby('shipment_id')['distance_km']
.transform('sum')
)

In [26]:
finalmerge['delivery_duration'] = (
finalmerge.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [27]:
finalmerge['late_delivery_flag'] = (
finalmerge.groupby('delivery_id')['is_late']
.transform('sum')
)

In [28]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,2.30,3,9,0,1,Long delivery distance,11.97,926.17,16.60,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,3.30,1,12,1,0,Normal delivery,73.29,63.22,1.06,0
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,4.09,1,19,2,0,Normal delivery,90.70,374.86,7.56,0
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.68,1,16,3,0,Normal delivery,13.26,148.44,3.35,0
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,4.18,1,17,4,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,4.04,1,6,999995,0,Normal delivery,5.33,59.99,1.33,0
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,4.29,2,16,999996,0,Normal delivery,7.11,235.68,3.63,0
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,4.38,1,13,999997,0,Normal delivery,12.26,100.23,2.01,0
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,4.64,1,5,999998,0,Normal delivery,10.37,46.44,1.17,0
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.57,1,17,999999,0,Normal delivery,14.78,185.89,4.37,0

In [29]:
#finalmerge[["shipment_id","shipment_weight","shipment_distance","delivery_duration","late_delivery_flag"]].drop_duplicates().merge(shipments_cleaned).to_csv("final_data/shipment_final.csv", index=False)

# Delivery Feature Engineering

In [30]:
import pandas as pd
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [31]:
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [32]:
deliveries_cleaned["delivery_weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [33]:
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [34]:
finalmerge

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,customer_rating,attempt_number,delivery_hour,Unnamed: 0,is_late,risk_reason,shipment_weight,shipment_distance,delivery_duration,late_delivery_flag
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,2.30,3,9,0,1,Long delivery distance,11.97,926.17,16.60,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,3.30,1,12,1,0,Normal delivery,73.29,63.22,1.06,0
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,4.09,1,19,2,0,Normal delivery,90.70,374.86,7.56,0
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.68,1,16,3,0,Normal delivery,13.26,148.44,3.35,0
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,4.18,1,17,4,0,Normal delivery,36.98,61.17,1.81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,4.04,1,6,999995,0,Normal delivery,5.33,59.99,1.33,0
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,4.29,2,16,999996,0,Normal delivery,7.11,235.68,3.63,0
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,4.38,1,13,999997,0,Normal delivery,12.26,100.23,2.01,0
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,4.64,1,5,999998,0,Normal delivery,10.37,46.44,1.17,0
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.57,1,17,999999,0,Normal delivery,14.78,185.89,4.37,0

In [35]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [36]:
deliveryMerged = pd.merge(
    finalmerge,
    all3merged,
    on="delivery_id",
    how="left"
)

In [37]:
deliveryMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,delivery_duration_hours_y,delivery_distance_km_y,fuel_cost_zar_y,customer_rating_y,attempt_number_y,delivery_hour_y,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,16.60,935.04,2504.92,2.30,3,9,6,87187.67,14531.278333,4.225000
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,1.06,57.08,115.77,3.30,1,12,9,556943.59,61882.621111,3.161111
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,7.56,402.48,891.87,4.09,1,19,12,682047.43,56837.285833,6.170833
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.35,147.70,609.51,3.68,1,16,14,364405.93,26028.995000,6.772857
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,1.81,54.77,122.58,4.18,1,17,11,242469.29,22042.662727,13.041818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,1.33,64.93,202.73,4.04,1,6,13,513060.49,39466.191538,7.640769
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,3.63,261.61,946.81,4.29,2,16,13,945833.66,72756.435385,4.793846
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,2.01,100.67,371.75,4.38,1,13,16,693765.03,43360.314375,6.315000
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,1.17,58.36,157.25,4.64,1,5,18,393822.40,21879.022222,6.840000
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.37,217.80,695.03,4.57,1,17,8,55380.60,6922.575000,9.558750

In [38]:
lastMerged = deliveryMerged.merge(deliveries_cleaned)

In [39]:
lastMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5

In [40]:
lastMerged['customer_average_distance'] = (
lastMerged.groupby('customer_id_x')['delivery_distance_km']
.transform('mean')
)
lastMerged["distance_vs_average"] =(lastMerged["delivery_distance_km"] / lastMerged["customer_average_distance"])
lastMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1,230.100000,4.063625
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,Delivered,1.06,57.08,115.77,3.30,1,12,5,152.032222,0.375447
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,Delivered,7.56,402.48,891.87,4.09,1,19,4,338.757500,1.188107
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,Delivered,3.35,147.70,609.51,3.68,1,16,1,380.225000,0.388454
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,Delivered,1.81,54.77,122.58,4.18,1,17,2,759.037273,0.072157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,Delivered,1.33,64.93,202.73,4.04,1,6,1,429.092308,0.151319
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,Delivered,3.63,261.61,946.81,4.29,2,16,1,275.552308,0.949402
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,Delivered,2.01,100.67,371.75,4.38,1,13,2,336.391250,0.299265
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,Delivered,1.17,58.36,157.25,4.64,1,5,2,381.967222,0.152788
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,Delivered,4.37,217.80,695.03,4.57,1,17,5,534.656250,0.407365

In [41]:
lastMerged['delivery_delay_hours'] = (
lastMerged.groupby('delivery_distance_km')['delivery_duration_hours']
.transform('mean')
)
lastMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average,delivery_delay_hours
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,16.60,935.04,2504.92,2.30,3,9,1,230.100000,4.063625,16.386667
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,1.06,57.08,115.77,3.30,1,12,5,152.032222,0.375447,1.462500
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,7.56,402.48,891.87,4.09,1,19,4,338.757500,1.188107,7.364286
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,3.35,147.70,609.51,3.68,1,16,1,380.225000,0.388454,3.099524
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,1.81,54.77,122.58,4.18,1,17,2,759.037273,0.072157,1.558125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,1.33,64.93,202.73,4.04,1,6,1,429.092308,0.151319,1.694063
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,3.63,261.61,946.81,4.29,2,16,1,275.552308,0.949402,4.885556
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,2.01,100.67,371.75,4.38,1,13,2,336.391250,0.299265,2.194324
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,1.17,58.36,157.25,4.64,1,5,2,381.967222,0.152788,1.700556
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,4.37,217.80,695.03,4.57,1,17,5,534.656250,0.407365,4.063077

In [42]:
lastMerged['late_delivery_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('sum')
)

In [43]:
lastMerged['long_distance_flag'] = (
lastMerged.groupby('delivery_id')['delivery_duration_hours']
.transform('mean')
)

In [44]:
lastMerged['repeat_delay_flag'] = (
lastMerged.groupby('attempt_number')['delivery_duration_hours']
.transform('count')
)
lastMerged

,Unnamed: 0_x_x,shipment_id_x,customer_id_x,warehouse_id_x,shipment_date_x,shipment_type_x,delivery_method_x,weight_kg_x,declared_value_zar_x,distance_km_x,...,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,customer_average_distance,distance_vs_average,delivery_delay_hours,long_distance_flag,repeat_delay_flag
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,2504.92,2.30,3,9,1,230.100000,4.063625,16.386667,16.60,15384
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,115.77,3.30,1,12,5,152.032222,0.375447,1.462500,1.06,888559
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,891.87,4.09,1,19,4,338.757500,1.188107,7.364286,7.56,888559
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,609.51,3.68,1,16,1,380.225000,0.388454,3.099524,3.35,888559
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,122.58,4.18,1,17,2,759.037273,0.072157,1.558125,1.81,888559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,202.73,4.04,1,6,1,429.092308,0.151319,1.694063,1.33,888559
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,946.81,4.29,2,16,1,275.552308,0.949402,4.885556,3.63,96057
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,371.75,4.38,1,13,2,336.391250,0.299265,2.194324,2.01,888559
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,157.25,4.64,1,5,2,381.967222,0.152788,1.700556,1.17,888559
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,695.03,4.57,1,17,5,534.656250,0.407365,4.063077,4.37,888559

In [45]:
#lastMerged[["delivery_id","delivery_hour", "delivery_weekday", "customer_shipment_count", "customer_average_delivery_time", "distance_vs_average", "delivery_delay_hours", "late_delivery_flag", "long_distance_flag", "repeat_delay_flag"]].drop_duplicates().merge(deliveries_cleaned).to_csv("final_data/deliveries_final.csv", index=False)

# DELIVERY DATE FEATURE (DATE FEATURES:)

In [46]:
#Converting object to datetime
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])

In [47]:
deliveries_cleaned["year"] = deliveries_cleaned["delivery_date"].dt.year

In [48]:
deliveries_cleaned["month"] = deliveries_cleaned["delivery_date"].dt.month

In [49]:
deliveries_cleaned["day"] = deliveries_cleaned["delivery_date"].dt.day

In [50]:
deliveries_cleaned["weekday"] = deliveries_cleaned["delivery_date"].dt.weekday

In [51]:
deliveries_cleaned["hour"] = deliveries_cleaned["delivery_hour"]

In [52]:
deliveries_cleaned["is_weekend"] = deliveries_cleaned["weekday"] >= 5

In [53]:
deliveries_cleaned

,Unnamed: 0,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,delivery_weekday,year,month,day,weekday,hour,is_weekend
0,0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9,1,2025,12,16,1,9,False
1,1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12,5,2025,3,22,5,12,True
2,2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19,4,2026,6,26,4,19,False
3,3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16,1,2026,7,21,1,16,False
4,4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17,2,2025,7,16,2,17,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6,1,2025,7,8,1,6,False
999996,999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16,1,2026,5,5,1,16,False
999997,999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13,2,2025,12,17,2,13,False
999998,999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5,2,2026,3,4,2,5,False
999999,999999,DL001000000,S001000000,D005538,V011867,2025-05-31,Delivered,4.37,217.80,695.03,4.57,1,17,5,2025,5,31,5,17,True

In [54]:
#deliveries_cleaned.to_csv("features_engineering/deliveries_date_feature.csv")

# SHIPMENTS DATE FEATURE

In [55]:
#Converting object to datetime
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])

In [56]:
shipments_cleaned["year"] = shipments_cleaned["shipment_date"].dt.year
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025

In [57]:
shipments_cleaned["month"] = shipments_cleaned["shipment_date"].dt.month
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5

In [58]:
shipments_cleaned["day"] = shipments_cleaned["shipment_date"].dt.day
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30

In [59]:
shipments_cleaned["weekday"] = shipments_cleaned["shipment_date"].dt.weekday
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4

In [60]:
# shipments_cleaned["hour"] = shipments_cleaned["delivery_hour"]

In [61]:
shipments_cleaned["is_weekend"] = shipments_cleaned["weekday"] >= 5
shipments_cleaned

,Unnamed: 0,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,year,month,day,weekday,is_weekend
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low,2025,12,14,6,True
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium,2025,3,21,4,False
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical,2026,6,23,1,False
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium,2026,7,21,1,False
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low,2025,7,15,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium,2025,7,4,4,False
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium,2026,5,3,6,True
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low,2025,12,12,4,False
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High,2026,3,1,6,True
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium,2025,5,30,4,False

In [62]:
#shipments_cleaned.to_csv("features_engineering/shipments_date_feature.csv")

# CUSTOMER DATE FEATURE

In [63]:
#Converting object to datetime
customers_cleaned.info()
customers_cleaned['registration_date'] = pd.to_datetime(customers_cleaned['registration_date'])

In [64]:
customers_cleaned["year"] = customers_cleaned["registration_date"].dt.year

In [65]:
customers_cleaned["month"] = customers_cleaned["registration_date"].dt.month

In [66]:
customers_cleaned["day"] = customers_cleaned["registration_date"].dt.day

In [67]:
customers_cleaned["weekday"] = customers_cleaned["registration_date"].dt.weekday

In [68]:
customers_cleaned["is_weekend"] = customers_cleaned["weekday"] >= 5
customers_cleaned

,Unnamed: 0,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,year,month,day,weekday,is_weekend
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,2024,10,13,6,True
1,1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50,2022,1,26,2,False
2,2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67,2019,3,4,0,False
3,3,C000004,Bongani Sithole,Individual,Kwazulu-Natal,Richards Bay,2021-06-30,10034.40,2021,6,30,2,False
4,4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38,2026,3,28,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,C099996,Dumisani Mkhize,Individual,Gauteng,Pretoria,2023-03-29,78517.63,2023,3,29,2,False
99996,99996,C099997,Thabo Mahlangu,Individual,Western Cape,Cape Town,2023-11-08,7369.63,2023,11,8,2,False
99997,99997,C099998,Kagiso Mthembu,Individual,Kwazulu-Natal,Newcastle,2023-04-27,9942.18,2023,4,27,3,False
99998,99998,C099999,Thabo Maseko,Individual,Western Cape,Stellenbosch,2020-06-08,838.25,2020,6,8,0,False
99999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,2019,8,31,5,True

In [69]:
#customers_cleaned.to_csv("features_engineering/customer_date_feature.csv")

In [70]:
#To access the shipment merged dataset
#data = pd.read_csv("""C:\\Users\\e1023443\\OneDrive - Sanlam Life Insurance Limited\\Desktop\\shipment_final.csv""")

In [71]:
#data

# Customer Analytics

In [72]:
customers_cleaned.info()

In [73]:
#1. How many customers does the company have?
total_customers = customers_cleaned['customer_id'].nunique()
print(f"Total customers: {total_customers}")

In [ ]:
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(4, 3))

ax.text (0.5, 0.55,f"{total_customers:,}", fontsize=48, ha="center", va="center", color="#0A2540", weight="bold") 
ax.text(0.5, 0.25, "Total Customers", fontsize = 14, ha="center", va="center", color="#2563EB")
ax.axis("off")
plt.tight_layout()
plt.show()

In [74]:
#2. Which province has the most customers?
customer_province = (
    customers_cleaned.groupby('province')['customer_id'].nunique().sort_values(ascending=False)
)
print(customer_province)
print("Province with the most customers:", customer_province.idxmax())

In [ ]:
#Define variables for Question 2
g = list(customer_province.index.values)[0:]
v = list(customer_province.values)[0:]

In [ ]:
#Creation of Bar Chart for Question 2
import matplotlib.pyplot as plt 

plt.bar(g, v, color="#003366", edgecolor= "black", linewidth=1.5)
plt.title("Provincial Breakdown of Total Customers")
plt.xlabel("Province")
plt.ylabel("Total Customers")
plt.xticks(rotation=45, ha="right")


plt.show()

In [75]:
shipping_by_segment = pd.merge(
    shipments_cleaned , 
    customers_cleaned, 
    on= "customer_id", 
    how= "left"
)
shipping_by_segment

,Unnamed: 0_x,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,...,customer_type,province,city,registration_date,monthly_shipping_budget,year_y,month_y,day_y,weekday_y,is_weekend_y
0,0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,...,Individual,Northern Cape,Upington,2022-06-12,33682.40,2022,6,12,6,True
1,1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,...,Individual,Gauteng,Pretoria,2019-06-02,1862.17,2019,6,2,6,True
2,2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,...,Individual,Eastern Cape,Grahamstown,2019-11-25,26477.64,2019,11,25,0,False
3,3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,...,Business,Mpumalanga,Nelspruit,2026-04-18,32574.97,2026,4,18,5,True
4,4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,...,Business,Free State,Welkom,2019-11-10,3591.22,2019,11,10,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,...,Individual,Eastern Cape,Gqeberha,2022-04-22,12873.22,2022,4,22,4,False
999996,999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,...,Individual,Eastern Cape,Mthatha,2019-05-28,1368.66,2019,5,28,1,False
999997,999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,...,Individual,North West,Potchefstroom,2020-12-18,5006.93,2020,12,18,4,False
999998,999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,...,Individual,Gauteng,Midrand,2022-10-13,11744.83,2022,10,13,3,False
999999,999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,...,Business,Free State,Welkom,2024-11-12,17916.59,2024,11,12,1,False

In [76]:
#3. Which customer segment sends the most shipment?
shipments_by_segment = (
    shipping_by_segment.groupby('customer_type')['shipment_id']
    .count()
    .sort_values(ascending=False)
)

print(shipments_by_segment)
print("The customer segment with the most shipments is:", shipments_by_segment.idxmax())

In [77]:
#Define variables for Question 3
h = list(shipments_by_segment.index.values)[0:]
d = list(shipments_by_segment.values)[0:]

In [ ]:
#Creation of Bar Chart for Question 3
plt.bar(h, d, color="#003366", edgecolor= "black", linewidth=1.5)
plt.title("Total Shipments by Customer")
plt.xlabel("Customer Segment")
plt.ylabel("Total Shipments")
#plt.xticks(rotation=45, ha="right")


plt.show()

In [78]:
all3merged

,Unnamed: 0_x,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,Unnamed: 0_y,shipment_id,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,100839.0,S000100840,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,167240.0,S000167241,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,285490.0,S000285491,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,352136.0,S000352137,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,366849.0,S000366850,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,198839.0,S000198840,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,270900.0,S000270901,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,550742.0,S000550743,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,638985.0,S000638986,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,771082.0,S000771083,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [79]:
#4. Which customer segment generate the highest shipping value?
shipping_value = (all3merged.groupby('customer_type')['customer_total_shipping_value'].sum().sort_values(ascending=False))
print(shipping_value)
print("The most customer shipping segment:", shipping_value.idxmax())

In [80]:
#Define variables for Question 4
a = list(shipping_value.index.values)[0:]
c = list(shipping_value.values)[0:]

                   frequent_ship
customer_name
Mpho Williams               2068
Precious Moyo               2062
Siyabonga Mthembu           2014
Bongani Mkhize              1995
Amanda Mthembu              1979
Tshepo Dlamini              1976
Tshepo Williams             1970
Phumzile Jacobs             1967
Thabo Moyo                  1962
Karabo Dlamini              1960

In [ ]:
#Creation of Bar Chart for Question 4
plt.bar(h, d, color="#003366", edgecolor= "black", linewidth=1.5)
plt.title("Total Shipment Value by Customer Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Total Shipment Value (R)")

plt.show()

In [ ]:
#5. Which customer have the highest shipment frequency? 
frequent_ship = all3merged.groupby("customer_name").agg(frequent_ship=("shipment_id","count"))
frequent_ship = frequent_ship.sort_values(by='frequent_ship', ascending=False).head(10)

frequent_ship

In [ ]:
#Creation of Bar Chart for Question 5
frequent_ship.plot(kind='bar')
plt.title("Top 10 Customers by Shipment Frequency")
plt.xlabel("Customer Name")
plt.ylabel("Number of Shipments")
plt.xticks(rotation=40, ha="right")

plt.show()

In [81]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [82]:
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [83]:
#6. Which customer experienced the most delayed deliveries? 
late_deliveries = finalmerge[finalmerge["delivery_status"] == "Delayed"]
deliveries = late_deliveries.groupby("customer_id").agg(
    deliveries=("delivery_status", "count")
)
deliveries.reset_index()
deliveries.sort_values(by='deliveries', ascending=False).head(10)

             deliveries
customer_id
C097972               6
C039665               5
C065659               5
C088313               5
C089637               5
C010211               4
C048350               4
C049297               4
C027552               4
C036807               4

In [84]:
top10 = (late_deliveries.groupby("customer_id")
.agg(deliveries=("delivery_status", "count"))
.sort_values(by="deliveries", ascending=False)
.head(10)
)

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
plt.figure(figsize=(12, 6))
plt.bar(
    top10.index.astype(str),
    top10["deliveries"]
)

plt.title("Top 10 Customers with Most Delayed Deliveries")
plt.xlabel("Customer ID")
plt.ylabel("Number of Delayed Deliveries")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Shipment Analytics

In [ ]:
#7. Which shipment types are most common? 
shipment_count = (
    shipments_cleaned.groupby('shipment_type')['customer_id'].nunique()
    .sort_values(ascending=False)
)
print(shipment_count)
print("Shipment type that are most common:", shipment_count.idxmax())

In [ ]:
#Creating a visualization for shipment types
import matplotlib.pyplot as plt 

shipment_count.plot(kind='bar')
plt.title("Most common Shipment Types")
plt.xlabel('Shipment Type')
plt.ylabel('Nummber of Customers')
plt.xticks(rotation=0)
#plt.tight_layout()
plt.show()

In [ ]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")

In [ ]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")

In [ ]:
delship = pd.merge(
    deliveries_cleaned,
    shipments_cleaned,
    on="shipment_id",
    how="left"
)

In [ ]:
#8. Which delivery method are most frequently used? 
frequent_delivery = delship.groupby("delivery_method").agg(frequent_delivery=
                                                           ("delivery_id","count"))
frequent_delivery.reset_index()
frequent_delivery.sort_values(by='frequent_delivery', ascending=False)

In [ ]:
#Creating a visualization for frequently used delivery methods
import matplotlib.pyplot as plt 

frequent_delivery.plot(kind='bar')
plt.title("Frequently used Delivery Methods")
plt.xlabel('Delivery Method')
plt.ylabel('How frequently is it used')
plt.xticks(rotation=0)
#plt.tight_layout()
plt.show()

In [ ]:
cust = delship.merge(customers_cleaned)
cust

In [ ]:
#9. Which province generates the most shipment volume?
province = cust.groupby("province").agg(province_shipment=("shipment_id","count"))
province.reset_index()
province.sort_values(by='province', ascending=False)

In [ ]:
#Creating a visualization for provinces with most shipment
import matplotlib.pyplot as plt 

province.plot(kind='bar')
plt.title("Pronvices with most Shipment")
plt.xlabel('Pronvinces')
plt.ylabel('Number of shipments')
plt.xticks(rotation=60)
#plt.tight_layout()
plt.show()

In [ ]:
#10. What are the busiest shipping days?
shipments_cleaned['shipment_date'] = pd.to_datetime(shipments_cleaned['shipment_date'])
busiest_days = shipments_cleaned['shipment_date'].dt.day_name().value_counts()
day_order = [
'Monday', 'Tuesday', 'Wednesday',
'Thursday', 'Friday', 'Saturday', 'Sunday'
]
busiest_days = busiest_days.reindex(day_order, fill_value=0)
print(busiest_days)

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(
    busiest_days.index,
    busiest_days.values,
    marker='o',
    linewidth=2,
    color='blue'
)

plt.title('Shipments by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Number of Shipments')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

In [ ]:
#11. How does shipment activity change over time?
cust['registration_date'] = pd.to_datetime(cust['registration_date'])

shipment_activity = (
    cust.groupby(cust['registration_date'].dt.to_period('M'))
    .agg(total_shipments=('shipment_id', 'count'))
    .head(12)
    .reset_index()
)
shipment_activity['registration_date'] = shipment_activity['registration_date'].astype(str)
print(shipment_activity)

In [ ]:
plt.figure(figsize=(10, 6))

plt.plot(
    shipment_activity['registration_date'],
    shipment_activity['total_shipments'],
    marker='o',
    linewidth=2
)

plt.title('Monthly Shipment Activity')
plt.xlabel('Month')
plt.ylabel('Total Shipments')
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

In [ ]:
#cust.columns

# Delivery Performance Analysis

In [ ]:
delivery_labels_cleaned

In [ ]:
#Analysis:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
delivery_labels_cleaned = pd.read_csv("cleaned_supplyguard_data/delivery_labels_cleaned.csv")
warehouses_cleaned = pd.read_csv("cleaned_supplyguard_data/warehouses_cleaned.csv")
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")


deliveries_cleaned
delivery_analy = deliveries_cleaned.merge(
    delivery_labels_cleaned[['delivery_id', 'is_late']],
    on='delivery_id',
    how='left'
)
delivery_analy = delivery_analy.merge(
    shipments_cleaned[['shipment_id', 'warehouse_id', 'shipment_type']],
    on='shipment_id',
    how='left'
)
delivery_analy = delivery_analy.merge(
    warehouses_cleaned[['warehouse_id', 'warehouse_name', 'province']],
    on='warehouse_id',
    how='left'
)

In [ ]:
delivery_analy

In [ ]:
#Late delivery rate 
late_deliver = delivery_labels_cleaned['is_late'].mean() * 100 
print("Late delivery rate:", late_deliver,"%")

In [ ]:
#Late delivery rate
late_deliver = delivery_labels_cleaned['is_late'].value_counts().sort_index()
late_deliver.index = ['On Time', 'Late']

late_deliver.plot(kind='pie', autopct='%1.1f%%')
plt.title("Late delivery rate")
plt.ylabel('')
plt.show()

In [ ]:
#Late deliveries by route 
shipment_route = shipments_cleaned.merge(
    warehouses_cleaned[['warehouse_id', 'city']],
    on='warehouse_id',
    how='left'
)
shipment_route = shipment_route.rename(
    columns={'city': 'warehouse_city'}
)

shipment_route = shipment_route.merge(
    customers_cleaned[['customer_id', 'city']],
    on='customer_id',
    how='left'
)
shipment_route = shipment_route.rename(
    columns={'city': 'customer_city'}
)

In [ ]:
warehouses_cleaned = pd.read_csv("cleaned_supplyguard_data/warehouses_cleaned.csv")
shipment_route['route'] = (shipment_route['warehouse_city'] + ' > ' + shipment_route['customer_city']
)
delivery_analy = delivery_analy.merge(
    shipment_route[['shipment_id', 'route']],
    on='shipment_id',
    how='left'

)
#Calculating late deliveries
late_by_route = (
    delivery_analy.groupby('route')['is_late'].mean().mul(100).sort_values(ascending=False)).head()
print(late_by_route)

In [ ]:
#Route column
shipment_route

In [ ]:
#Late deliveries by driver 
delivery_analy = deliveries_cleaned.merge(
    delivery_labels_cleaned[['delivery_id', 'is_late']],
    on='delivery_id',
    how='left'
)

late_driver = (delivery_analy.groupby('driver_id')['is_late'].mean().mul(100).sort_values(ascending=False).head())
print(late_driver)

In [ ]:
late_driver.plot(kind='bar')

plt.title('Late delivery rate by Driver')
plt.xlabel('Driver ID')
plt.ylabel('Late delivery rate (%)')
plt.xticks(rotation=0)
plt.show()

In [ ]:
#Late deliveries by vehicle 
vehicle_late = (
    delivery_analy.groupby('vehicle_id')['is_late'].mean().mul(100).sort_values(ascending=False).head()
)
print(vehicle_late)

In [ ]:
#Late deliveries by warehouse 
warehouse_late = (
    delivery_analy.groupby('warehouse_id')['is_late'].mean().mul(100).sort_values(ascending=False).head()
)
print(warehouse_late)

In [ ]:
#Late deliveries by province 
late_by_province = (
    delivery_analy.groupby('province')['is_late'].mean().mul(100).sort_values(ascending=False).head()
)
print(late_by_province)

In [ ]:
#Late deliveries by shipment type 
late_by_ship = (
    delivery_analy.groupby('shipment_type')['is_late'].mean().mul(100).sort_values(ascending=False).head()
)
print(late_by_ship)

In [ ]:
#Late deliveries by delivery time 
late_by_deliv_time = (
    delivery_analy.groupby('delivery_hour')['is_late'].mean().mul(100).sort_values(ascending=False).head()
)
print("Delivery late by: ", late_by_deliv_time)

# Business Intellengence - Operation

In [ ]:
deliveries_cleaned

In [ ]:
#1. How many deliveries are late?
late_delivery = (deliveries_cleaned['delivery_status'] == 'Delivered Late').sum()
print("Number of late deliveries: ", late_delivery)

In [ ]:
fig, ax = plt.subplots(figsize=(5, 3))
ax.axis('off')
ax.text(
    0.5, 0.6,
    f"{late_delivery:,}",
    ha='center',
    va='center',
    fontsize=30,
    fontweight='bold',
    color='blue'
)

ax.text(
    0.5, 0.3,
    "Late Deliveries",
    ha='center',
    va='center',
    fontsize=14
)

plt.title("", pad=10)
plt.show()

In [ ]:
#2. What percentage of deliveries are late?
late_percentange = ((deliveries_cleaned['delivery_status'] == 'Delivered Late').sum()
/ len(deliveries_cleaned)) * 100
print("Percentange of late deliveries:", late_percentange)

In [ ]:
late_percentange = deliveries_cleaned['delivery_status'].value_counts()
late_percentange.plot(
    kind='pie',
    autopct= '%1.1f%%'
)
plt.title('Percentange of Delivery by status')
plt.ylabel('')
plt.show()

In [ ]:
warehouse_cleaned = pd.read_csv("cleaned_supplyguard_data/warehouses_cleaned.csv")
warehouse_cleaned

In [ ]:
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")
customers_cleaned

In [ ]:
#3. Which routes have the highest late-delivery rate?
route_df = deliveries_cleaned.merge(
shipments_cleaned[['shipment_id', 'warehouse_id', 'customer_id']],
on='shipment_id'
)


route_df = route_df.merge(
warehouse_cleaned[['warehouse_id', 'city']],
on='warehouse_id'
).rename(columns={'city': 'warehouse_city'})

route_df = route_df.merge(
customers_cleaned[['customer_id', 'city']],
on='customer_id'
).rename(columns={'city': 'customer_city'})


route_df['route'] = (
route_df['warehouse_city'] + ' → ' + route_df['customer_city']
)

route_stats = (
route_df.groupby('route')
.agg(
total_deliveries=('delivery_id', 'count'),
late_deliveries=('delivery_status',
lambda x: (x == 'Delivered Late').sum())
)
.reset_index()
)

route_stats['late_delivery_rate (%)'] = (
route_stats['late_deliveries']
/ route_stats['total_deliveries']
* 100
).round(2)

route_stats.sort_values(
'late_delivery_rate (%)',
ascending=False
).head(10)

In [ ]:
# Get top 10 routes
top_routes = (
    route_stats.sort_values(
        'late_delivery_rate (%)',
        ascending=False
    )
    .head(10)
)

plt.figure(figsize=(12, 6))

plt.barh(
    top_routes['route'],
    top_routes['late_delivery_rate (%)'],
    color='blue'
)

plt.title('Top 10 Routes with Highest Late Delivery Rate')
plt.xlabel('Late Delivery Rate (%)')
plt.ylabel('Route')


plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

In [ ]:
drivers_cleaned = pd.read_csv("cleaned_supplyguard_data/drivers_cleaned.csv")
drivers_cleaned

In [ ]:
#4. Which drivers have the highest delay rates?
deliveries_cleaned['is_late'] = deliveries_cleaned['delivery_status'].eq('Delivered Late')

# Calculate delay rate per driver
driver_delay_rates = (
deliveries_cleaned.groupby('driver_id')
.agg(
total_deliveries=('delivery_id', 'count'),
late_deliveries=('is_late', 'sum')
)
.reset_index()
)

driver_delay_rates['delay_rate (%)'] = (
driver_delay_rates['late_deliveries']
/ driver_delay_rates['total_deliveries']
* 100
).round(2)


driver_delay_rates = driver_delay_rates.sort_values(
by='delay_rate (%)',
ascending=False
)

driver_delay_rates.head(10)

In [ ]:
#5.Which vehicle are associated with the most delays?
deliveries_cleaned.tail(10)

In [ ]:
deliveries_cleaned['delivery_status'].describe()
deliveries_cleaned['delivery_status'].value_counts()

In [ ]:
vehicles_cleaned = pd.read_csv("cleaned_supplyguard_data/vehicles_cleaned.csv")
vehicles_cleaned

In [ ]:
delays = deliveries_cleaned[deliveries_cleaned['delivery_status'] == 'Delayed']
print(f"Total Delayed Deliveries: {len(delays ):}")
vehicle_delays = (delays.groupby('vehicle_id').size().sort_values(ascending=False).head(10))
print("\nTop 10 vehicles with the most delays:")
print(vehicle_delays)
# vehicle_perfomance = deliveries_cleaned.groupby('vehicle_id').agg(total_deliveries=('delivery_id', 'count'), total_delays=('delivery_status', lambda x: (x == 'Delivered Late').sum()))
# vehicle_perfomance =vehicle_perfomance['total_delays']
# vehicle_perfomance.head(10)

In [ ]:
plt.figure(figsize=(10, 6))

vehicle_delays.plot(kind='bar')

plt.title('Top 10 Vehicles Associated with the most Delays')
plt.xlabel('Vehicle ID')
plt.ylabel('Number of Delayed Deliveries')
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

In [ ]:
#6. Which warehouse have the highest operational risk?
warehouses_cleaned = pd.read_csv("cleaned_supplyguard_data/warehouses_cleaned.csv")
warehouses_cleaned

In [ ]:
shipments_cleaned

In [ ]:
warehouses_cleaned['warehouse_type'].value_counts()

In [ ]:
warehouse_risk = (warehouses_cleaned.groupby('warehouse_type')['capacity_units'].mean().sort_values(ascending=False))

print("\nAverage capacity by warehosues type:")
print(warehouse_risk)

highets_risk = warehouse_risk.idxmax()
highets_risk_value = warehouse_risk.max()


print("\nWarehosues type with the highest operational risk:")
print(highets_risk)

print(f"Average capacity: {highets_risk_value:,.0f} units")

In [ ]:
plt.figure(figsize=(10, 6))

warehouse_risk.plot(kind='bar')

plt.title('Average Capacity by Warebouse Type')
plt.xlabel('Warebouse Type')
plt.ylabel('Average Capacity (Units)')
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

In [ ]:
#7. What times of day show the greatest delivery delays?
deliveries_cleaned

In [ ]:
late_by_hour = deliveries_cleaned[deliveries_cleaned['is_late'] == 1].groupby('delivery_hour').size().sort_index()

print("\nLate deliveries by hour:")
print(late_by_hour)

highets_delay_hour = late_by_hour.idxmax()
highets_delay_count = late_by_hour.max()

print("\nHour with the greatest number of deliveries delays:")
print(f"{highets_delay_hour}:00")
print(f"Number of late deliveries: {highets_delay_count:,}")

In [ ]:
plt.figure(figsize=(10, 6))

late_by_hour.plot(kind='bar')

plt.title('Late Deliveries by Time of Day')
plt.xlabel('Deliveries Hour')
plt.ylabel('Number of Late Deliveries')
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

# Business Intelligence - Management

In [ ]:
#8. What are the three biggest operational risks?
warehouses_cleaned

In [ ]:
warehouses_cleaned.warehouse_type.unique()

In [ ]:
warehouses_risk = warehouses_cleaned['warehouse_type'].value_counts().head(3)

print("Warebouse by Type:")
print(warehouses_risk)

biggest_risk = warehouses_risk.idxmax()
biggest_risk_count = warehouses_risk.max()

print("\nBiggest operational risk:")
print(f"{biggest_risk} ({biggest_risk_count})")

In [ ]:
plt.figure(figsize=(8, 5))

warehouses_risk.plot(kind='bar')

plt.title('Warebouse by Type - Operational Risk')
plt.xlabel('Warebouse Type')
plt.ylabel('Number of Warehouses')
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

In [ ]:
#9. What should management investigate?
print("Management should investigate the areas with the highest late delivery rates")

In [ ]:
fig, ax = plt.subplots(figsize=(2, 1))#Create the figure and axes that my visual KPI card will be placed on 

ax.text(0.5, 0.25, "Management should investigate the areas with the highest late delivery rates", fontsize = 14, ha="center", va="center", color="#2563EB") 
ax.axis("off")
plt.show()

In [ ]:
# 10.What operational controls could redude delivery delays?
print("1. Better route planning.")
print("2. Regular vehicle maintanance.")
print("3. Monitor high risk drivers.")
print("4. Monitor warehouses processing times.")
print("5. Schedule deliveries outiside peak delay periods.")
print("6. Track late deliveries in real time.")
print("7. Have backup vehicles and drivers available.")

In [ ]:
drivers_cleaned = pd.read_csv("cleaned_supplyguard_data/drivers_cleaned.csv")
drivers_cleaned

In [ ]:
# drivers_cleaned(drivers_cleaned['perfomance_rating'] == 'D004532')

In [ ]:

drivers_cleaned.groupby('driver_id')['performance_rating'].sum().sort_values(ascending=True).head(1)

In [ ]:
vehicles_cleaned

In [ ]:
drivers = drivers_cleaned.groupby('driver_id')['performance_rating'].sum().sort_values(ascending=True).head(1)

In [ ]:
vehicles_cleaned.groupby('vehicle_id')['maintenance_score'].sum().sort_values(ascending=True).head(1)

In [ ]:
warehouses_risk

In [ ]:
warehouses_cleaned

In [ ]:
warehouses_cleaned.groupby('warehouse_type')['capacity_units'].sum().sort_values(ascending=False).head(1)

In [ ]:
#11. Which routes, drivers, vehicles or warehouses require attention?
route = "Mindrad > Unknown"
print("1. Routes that require attention the most is: ", route, "because it has the highest late delivery rate.")
print("2. Drivers that require attention the most is: ", 'Driver ID: D004532', ', Rate: 1.68') #drivers
print("3. Vehicles that require attention the most is: ", 'Vehicle ID: V014247 maintenance is 30.0 ')
print("4. Warehouses that require attention the most is: ", 'Warehouse type:' ' Fulfilment 16015101 because of it capacity units')

In [ ]:
#12. How could the company improve customer satisfaction?
print("1. Reducing late deliveries.")
print("2. Providing accurate delivery times.")
print("3. Sending customer delay notifications.")
print("4. Improving communication with customers.")
print("5. Priotising high-value/urgent deliveries.")
print("6. Following up on failed delivery attempts.")

In [ ]:
#End..