# Customer Feature Engineering

In [216]:
import pandas as pd
customers_cleaned = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")

In [ ]:
shipments_cleaned = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
shipments_cleaned

In [ ]:
deliveries_cleaned = pd.read_csv("cleaned_supplyguard_data/deliveries_cleaned.csv")
deliveries_cleaned

In [219]:
#Merging datasets (customers & shipments)
mergedcusship = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [220]:
all3merged = mergedcusship.merge(deliveries_cleaned)

In [235]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [222]:
#Customer shipment count
all3merged['customer_shipment_count'] = (
all3merged.groupby('customer_id')['shipment_id']
.transform('count')
)

In [259]:
all3merged

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,...,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour,customer_shipment_count,customer_total_shipping_value,customer_average_shipment_value,customer_average_delivery_time
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,...,1.35,25.06,109.08,5.00,1,6,9,294834.78,32759.420000,10.330000
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,...,14.88,909.27,2003.65,5.00,1,15,9,294834.78,32759.420000,10.330000
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,...,36.08,2160.12,9141.59,2.37,2,18,9,294834.78,32759.420000,10.330000
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,...,2.63,125.13,277.69,4.28,1,9,9,294834.78,32759.420000,10.330000
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,...,5.46,364.37,991.26,4.94,1,16,9,294834.78,32759.420000,10.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,...,4.37,191.56,490.38,4.79,1,21,6,76602.31,12767.051667,3.886667
999996,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,...,4.62,271.75,896.37,4.61,1,16,6,76602.31,12767.051667,3.886667
999997,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,...,2.12,54.35,115.68,4.31,2,13,6,76602.31,12767.051667,3.886667
999998,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,...,6.95,393.81,1495.15,3.98,1,18,6,76602.31,12767.051667,3.886667
999999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,...,1.86,64.62,232.66,4.71,1,6,6,76602.31,12767.051667,3.886667

In [224]:
#Creating customer total shipments
all3merged['customer_total_shipping_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'] 
.transform('sum')
)

In [ ]:
all3merged

In [226]:
#Creating customer average shipment
all3merged['customer_average_shipment_value'] = (
all3merged.groupby('customer_id')['declared_value_zar'].
transform('mean')
)

In [227]:
all3merged

In [ ]:
# cust_deliv = deliveries_cleaned.merge(
#     shipments_cleaned[["shipment_id", "customer_id"]],
#     on="shipment_id",
#     how="left"
# )

In [ ]:
# cust_deliv

In [228]:
all3merged['customer_average_delivery_time'] = (
all3merged.groupby('customer_id')['delivery_duration_hours']
.transform('mean')
)

In [ ]:
#All 4 features
all3merged

# Date Features

In [ ]:
#Converting object to datetime
deliveries_cleaned['delivery_date'] = pd.to_datetime(deliveries_cleaned['delivery_date'])
deliveries_cleaned["delivery_date"].head(10)

In [ ]:
deliveries_cleaned["year"] = deliveries_cleaned["delivery_date"].dt.year

In [ ]:
deliveries_cleaned

In [ ]:
deliveries_cleaned["month"] = deliveries_cleaned["delivery_date"].dt.month
deliveries_cleaned

In [ ]:
deliveries_cleaned["day"] = deliveries_cleaned["delivery_date"].dt.day
deliveries_cleaned

In [ ]:
deliveries_cleaned["weekday"] = deliveries_cleaned["delivery_date"].dt.weekday
deliveries_cleaned

In [ ]:
deliveries_cleaned["hour"] = deliveries_cleaned["delivery_hour"]
deliveries_cleaned

In [ ]:
deliveries_cleaned["is_weekend"] = deliveries_cleaned["weekday"] >= 5
deliveries_cleaned