# Customer Feature Engineering

In [65]:
import pandas as pd
data = pd.read_csv("cleaned_supplyguard_data/customers_cleaned.csv")
data

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20
1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50
2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67
3,C000004,Bongani Sithole,Individual,Kwazulu-Natal,Richards Bay,2021-06-30,10034.40
4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38
...,...,...,...,...,...,...,...
99995,C099996,Dumisani Mkhize,Individual,Gauteng,Pretoria,2023-03-29,78517.63
99996,C099997,Thabo Mahlangu,Individual,Western Cape,Cape Town,2023-11-08,7369.63
99997,C099998,Kagiso Mthembu,Individual,Kwazulu-Natal,Newcastle,2023-04-27,9942.18
99998,C099999,Thabo Maseko,Individual,Western Cape,Stellenbosch,2020-06-08,838.25
99999,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92

In [66]:
data = pd.read_csv("cleaned_supplyguard_data/shipments_cleaned.csv")
data

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
999995,S000999996,C083745,W00142,2025-07-04,Standard,Courier,5.33,6355.05,59.99,Medium
999996,S000999997,C025118,W00123,2026-05-03,Bulk,Freight,7.11,9506.09,235.68,Medium
999997,S000999998,C093945,W00041,2025-12-12,Standard,Courier,12.26,3713.83,100.23,Low
999998,S000999999,C003920,W00130,2026-03-01,Standard,Road,10.37,14523.73,46.44,High
999999,S001000000,C029738,W00056,2025-05-30,Standard,Road,14.78,11580.34,185.89,Medium

In [67]:
#Merging datasets (customers & shipments)
data = pd.merge(
    customers_cleaned,
    shipments_cleaned,
    on='customer_id',
    how ='left'
)

In [68]:
data

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,Standard,Air,62.37,88332.07,24.36,Medium
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,Express,Road,3.36,717.55,992.27,Medium
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,Standard,Courier,1.51,1155.01,2278.10,High
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,Express,Road,3.69,452.60,134.92,Low
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,Standard,Road,19.40,26929.27,386.14,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000003,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,Bulk,Road,17.74,19197.13,160.11,Medium
1000004,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,Express,Courier,22.97,10494.67,237.30,Medium
1000005,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,Same Day,Road,0.50,731.48,46.50,Low
1000006,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,Express,Air,13.18,18452.44,381.30,Medium
1000007,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,Same Day,Air,3.40,172.54,57.35,Medium

In [69]:
#Customer shipment count
data['customer_shipment_count'] = (
data.groupby('customer_id')['shipment_id']
.transform('count')
)

In [70]:
data

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget,shipment_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority,customer_shipment_count
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000100840,W00040,2026-07-21,Standard,Air,62.37,88332.07,24.36,Medium,9
1,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000167241,W00219,2025-06-20,Express,Road,3.36,717.55,992.27,Medium,9
2,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000285491,W00071,2026-01-27,Standard,Courier,1.51,1155.01,2278.10,High,9
3,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000352137,W00057,2025-09-25,Express,Road,3.69,452.60,134.92,Low,9
4,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20,S000366850,W00016,2025-09-25,Standard,Road,19.40,26929.27,386.14,Medium,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000003,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000198840,W00201,2026-04-18,Bulk,Road,17.74,19197.13,160.11,Medium,6
1000004,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000270901,W00122,2026-04-13,Express,Courier,22.97,10494.67,237.30,Medium,6
1000005,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000550743,W00132,2025-11-04,Same Day,Road,0.50,731.48,46.50,Low,6
1000006,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000638986,W00062,2025-10-22,Express,Air,13.18,18452.44,381.30,Medium,6
1000007,C100000,Phumzile Modise,Individual,Kwazulu-Natal,Durban,2019-08-31,69674.92,S000771083,W00011,2025-07-29,Same Day,Air,3.40,172.54,57.35,Medium,6

In [ ]:
#Creating customer total shipments
data['customer_total_shipping_value'] = (
data.groupby('customer_id')['shipment_id'] #to be fixed..
.transform('sum')
)

In [ ]:
data

In [74]:
#Creating customer average shipment
data['customer_average_shipment_value'] = (
data.groupby('customer_id')['weight_kg'].
transform('mean')
)

In [ ]:
data

In [ ]:
# data['customer_average_delivery_time'] = (
# data.groupby('customer_id')['']
# .transform('mean')
# )