In [53]:
import pandas as pd 
import numpy as np

# OPERATIONAL LATE RISK SOCRING

In [ ]:
shipment = pd.read_csv("Final_data/shipment_final.csv")

In [55]:
#Make a copy of the cleaned dataset 
shipment_2 = shipment.copy()

In [ ]:
print("Late Delivery Flag:")
print(shipment_2["late_delivery_flag"].value_counts())

# Late_Delivery_Score  = np.where(shipment_2["late_delivery_flag"] == 1, 25, 0)

In [65]:
shipment_2["late_delivery_score"]= np.where(shipment_2["late_delivery_flag"] == 1, 25, 0)

#Check the results 
shipment_2[["late_delivery_flag", "late_delivery_score"]].head(10)

   late_delivery_flag  late_delivery_score
0                   1                   25
1                   0                    0
2                   0                    0
3                   0                    0
4                   0                    0
5                   0                    0
6                   0                    0
7                   1                   25
8                   0                    0
9                   0                    0

In [69]:
#Check the results 
print("==== Delivery Risk Score ====")
print(shipment_2[["late_delivery_flag", "late_delivery_score"]].head(10))

==== Delivery Risk Score ====
   late_delivery_flag  late_delivery_score
0                   1                   25
1                   0                    0
2                   0                    0
3                   0                    0
4                   0                    0
5                   0                    0
6                   0                    0
7                   1                   25
8                   0                    0
9                   0                    0

In [70]:
#4. Count how many shipments recieved the 25 points
late_shipments = (shipment_2["late_delivery_flag"] == 1).sum()
print("Number of late Shipments:", late_shipments)

Number of late Shipments: 153201

In [75]:
#5 Caculate the percentage of late shipments 
total_shipments =len(shipment_2)

late_percentage =(late_shipments / total_shipments) * 100
print(f"Percentage of late shipments: {late_percentage:.2f}%")

Percentage of late shipments: 15.32%

In [76]:
#6. Display the final late-delivery results 
late_delivery_results = shipment_2[["late_delivery_flag", "late_delivery_score"]].head(10)
late_delivery_results

   late_delivery_flag  late_delivery_score
0                   1                   25
1                   0                    0
2                   0                    0
3                   0                    0
4                   0                    0
5                   0                    0
6                   0                    0
7                   1                   25
8                   0                    0
9                   0                    0